-- Menu content is no longer seeded from this file.
--
-- This held the invented placeholder menu from the Figma export ("Mantel
-- Latte", "Crimson Cortado" …). The real menu now lives in
-- 007_menu_content.sql, which both removes those placeholders and loads the
-- actual items — so a fresh database and an existing one take the same path
-- and there is one source of truth for what the café sells.
--
-- Fresh database: schema.sql → 002 → 003 → 004 → 005 → 006 → 007.
