/*
 * Arabic for every dashboard string, keyed by the English sentence used at the
 * call site. Missing keys fall back to English (see i18n.tsx). Run
 * `node scripts/admin-i18n-check.mjs` to list anything not yet translated.
 */
export const AR: Record<string, string> = {
  // ── Navigation and shell ──
  "Today": "اليوم",
  "Orders": "الطلبات",
  "Menu": "المنيو",
  "Retail shop": "المتجر",
  "Website pages": "صفحات الموقع",
  "Photo library": "مكتبة الصور",
  "Customers": "العملاء",
  "Messages": "الرسائل",
  "Marketing": "التسويق",
  "Reports": "التقارير",
  "Shop settings": "إعدادات المحل",
  "Payments": "المدفوعات",
  "Team": "الفريق",
  "Site health": "صحة الموقع",
  "My account": "حسابي",
  "Run the café": "إدارة المقهى",
  "Website": "الموقع",
  "People": "الناس",
  "Grow": "النمو",
  "Setup": "الإعداد",
  "Staff": "الموظفون",
  "Mantel staff": "فريق مانتل",
  "Mantel — Staff": "مانتل — الفريق",
  "Search": "بحث",
  "Dashboard navigation": "قائمة لوحة التحكم",
  "Open menu": "فتح القائمة",
  "Open the website": "فتح الموقع",
  "Sign out": "تسجيل الخروج",
  "Lock": "قفل",
  "Theme: {mode}": "المظهر: {mode}",
  "Automatic": "تلقائي",
  "Light": "فاتح",
  "Dark": "داكن",
  "{n} need attention": "{n} بحاجة لمتابعة",
  "{n} new": "{n} جديد",
  "Your role doesn't include this section": "صلاحيتك لا تشمل هذا القسم",
  "Ask an admin to change what your role can do under Team → Permissions.": "اطلب من المدير تعديل صلاحياتك من الفريق ← الصلاحيات.",
  "This screen is being built": "هذه الشاشة قيد الإنشاء",
  "It will appear here in the next update.": "ستظهر هنا في التحديث القادم.",
  "Admin": "مدير النظام",
  "Manager": "مدير",
  "Support": "دعم",
  "Good morning": "صباح الخير",
  "Good afternoon": "مساء الخير",
  "Good evening": "مساء الخير",

  // ── Common words and actions ──
  "Add": "إضافة",
  "All": "الكل",
  "Archive": "أرشفة",
  "Archived": "مؤرشف",
  "Back": "رجوع",
  "Cancel": "إلغاء",
  "Clear": "مسح",
  "Clear search": "مسح البحث",
  "Close": "إغلاق",
  "Delete": "حذف",
  "Delete for good": "حذف نهائي",
  "Discard": "تجاهل",
  "Dismiss": "إخفاء",
  "Duplicate": "نسخ",
  "Email": "البريد الإلكتروني",
  "English": "الإنجليزية",
  "Hidden": "مخفي",
  "Leave": "مغادرة",
  "Loading…": "جارٍ التحميل…",
  "Name": "الاسم",
  "Now": "الآن",
  "On": "مفعّل",
  "Open": "مفتوح",
  "optional": "اختياري",
  "Phone": "الهاتف",
  "Preview": "معاينة",
  "Price": "السعر",
  "Remove": "إزالة",
  "Remove {v}": "إزالة {v}",
  "Restore": "استعادة",
  "Results": "النتائج",
  "Save": "حفظ",
  "Save changes": "حفظ التغييرات",
  "Select": "تحديد",
  "Show": "عرض",
  "Status": "الحالة",
  "Total": "المجموع",
  "Try again": "حاول مجدداً",
  "Undo": "تراجع",
  "Verify": "تحقق",
  "WhatsApp": "واتساب",
  "Why": "السبب",
  "Yes, continue": "نعم، متابعة",
  "Unsaved changes": "تغييرات غير محفوظة",
  "You have unsaved changes": "لديك تغييرات غير محفوظة",
  "What does this mean?": "ماذا يعني هذا؟",
  "This didn't load": "لم يتم التحميل",
  "Type \"{word}\" to confirm": "اكتب \"{word}\" للتأكيد",
  "just now": "الآن",
  "{n} min ago": "قبل {n} دقيقة",
  "{n} h ago": "قبل {n} ساعة",
  "{n} days ago": "قبل {n} يوم",
  "Sunday": "الأحد",
  "Monday": "الاثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": "الخميس",
  "Friday": "الجمعة",
  "Saturday": "السبت",
  "Open screen": "فتح الشاشة",
  "Order number, customer, item or screen…": "رقم الطلب، العميل، الصنف أو الشاشة…",
  "Nothing found. Try an order number like MTL-1A2B3C, a name, or an email.": "لا توجد نتائج. جرّب رقم طلب مثل MTL-1A2B3C أو اسماً أو بريداً إلكترونياً.",
  "Leave blank to use the English": "اتركه فارغاً لاستخدام النص الإنجليزي",

  // ── Errors ──
  "Something went wrong. Please try again.": "حدث خطأ ما. حاول مرة أخرى.",
  "Couldn't reach the server. Check the internet connection and try again.": "تعذّر الوصول إلى الخادم. تحقق من الإنترنت وحاول مجدداً.",
  "You don't have permission to do this. Ask an admin to give your role access.": "ليست لديك صلاحية لهذا الإجراء. اطلب من المدير منح صلاحيتك.",
  "That name or code is already used. Choose a different one.": "هذا الاسم أو الرمز مستخدم بالفعل. اختر غيره.",
  "An item needs a price above zero before it can be shown on the website.": "يجب أن يكون للصنف سعر أكبر من صفر قبل عرضه على الموقع.",
  "One of the values isn't allowed. Check the numbers and try again.": "إحدى القيم غير مسموح بها. تحقق من الأرقام وحاول مجدداً.",
  "This is still linked to something else, so it can't be removed. Try archiving it instead.": "هذا مرتبط بشيء آخر ولا يمكن حذفه. جرّب أرشفته بدلاً من ذلك.",
  "One of the values isn't valid.": "إحدى القيم غير صحيحة.",
  "That record no longer exists. Refresh the page.": "هذا السجل لم يعد موجوداً. حدّث الصفحة.",

  // ── Sign in ──
  "Sign in to the dashboard": "الدخول إلى لوحة التحكم",
  "Reset your password": "إعادة تعيين كلمة المرور",
  "For the Mantel team only.": "لفريق مانتل فقط.",
  "Enter your email and we'll send you a link to choose a new password.": "أدخل بريدك وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.",
  "Password": "كلمة المرور",
  "Show password": "إظهار كلمة المرور",
  "Hide password": "إخفاء كلمة المرور",
  "Sign in": "دخول",
  "Send reset link": "إرسال رابط إعادة التعيين",
  "Forgot password?": "نسيت كلمة المرور؟",
  "Back to sign in": "العودة لتسجيل الدخول",
  "Back to the website": "العودة إلى الموقع",
  "Check your email": "تحقق من بريدك",
  "If {email} belongs to a Mantel account, a link to set a new password is on its way. It can take a minute, and sometimes lands in spam.": "إذا كان {email} مرتبطاً بحساب في مانتل، فرابط تعيين كلمة المرور في الطريق. قد يستغرق دقيقة، وأحياناً يصل إلى البريد المزعج.",
  "Enter the email address you use for Mantel.": "أدخل البريد الإلكتروني الذي تستخدمه في مانتل.",
  "This email hasn't been confirmed yet. Open the link we emailed you first.": "لم يتم تأكيد هذا البريد بعد. افتح الرابط الذي أرسلناه لك أولاً.",
  "That email and password don't match. Check them, or reset the password.": "البريد وكلمة المرور غير متطابقين. تحقق منهما أو أعد تعيين كلمة المرور.",
  "Too many attempts. Wait a minute and try again.": "محاولات كثيرة. انتظر دقيقة وحاول مجدداً.",
  "Too many attempts. Wait a few minutes and try again.": "محاولات كثيرة. انتظر بضع دقائق وحاول مجدداً.",
  "Couldn't sign in right now. Check the connection and try again.": "تعذّر تسجيل الدخول الآن. تحقق من الاتصال وحاول مجدداً.",
  "This account isn't on the team": "هذا الحساب ليس ضمن الفريق",
  "Couldn't check your access": "تعذّر التحقق من صلاحيتك",
  "{email} is signed in, but it hasn't been added to the Mantel team. Ask an admin to invite this email under Team.": "تم تسجيل الدخول بـ {email} لكنه غير مضاف إلى فريق مانتل. اطلب من المدير دعوته من قسم الفريق.",
  "Check again": "تحقق مرة أخرى",
  "Sign in with a different account": "الدخول بحساب آخر",
  "Choose a new password": "اختر كلمة مرور جديدة",
  "New password": "كلمة المرور الجديدة",
  "At least 8 characters.": "8 أحرف على الأقل.",
  "Type it again": "اكتبها مرة أخرى",
  "Save password": "حفظ كلمة المرور",
  "Use at least 8 characters.": "استخدم 8 أحرف على الأقل.",
  "The two passwords don't match.": "كلمتا المرور غير متطابقتين.",
  "Couldn't save the new password. Open the link from the email again.": "تعذّر حفظ كلمة المرور. افتح الرابط من البريد مرة أخرى.",

  // ── Two-step and PIN ──
  "Two-step sign-in": "الدخول بخطوتين",
  "The team has turned on two-step sign-in. It keeps customer details safe even if a password is guessed.": "فعّل الفريق الدخول بخطوتين. يحمي بيانات العملاء حتى لو تم تخمين كلمة المرور.",
  "1. Install an authenticator app on your phone, such as Google Authenticator or Microsoft Authenticator.": "١. ثبّت تطبيق مصادقة على هاتفك مثل Google Authenticator أو Microsoft Authenticator.",
  "2. In the app, add an account and scan this code:": "٢. في التطبيق، أضف حساباً وامسح هذا الرمز:",
  "3. Enter the 6-digit code the app shows:": "٣. أدخل الرمز المكوّن من 6 أرقام الظاهر في التطبيق:",
  "QR code for your authenticator app": "رمز QR لتطبيق المصادقة",
  "Can't scan? Type this key into the app instead:": "لا يمكنك المسح؟ اكتب هذا المفتاح في التطبيق:",
  "Open your authenticator app and enter the 6-digit code for Mantel.": "افتح تطبيق المصادقة وأدخل رمز مانتل المكوّن من 6 أرقام.",
  "6-digit code": "رمز من 6 أرقام",
  "That code didn't work. Codes change every 30 seconds — use the newest one.": "الرمز غير صحيح. تتغير الرموز كل 30 ثانية — استخدم أحدثها.",
  "Couldn't start two-step setup. Try again in a moment.": "تعذّر بدء إعداد الدخول بخطوتين. حاول بعد قليل.",
  "Counter locked": "الجهاز مقفل",
  "Who's at the counter?": "من على الكاونتر؟",
  "Enter your PIN": "أدخل رمزك السري",
  "{n} of 4 digits entered": "تم إدخال {n} من 4 أرقام",
  "Delete digit": "حذف رقم",
  "Wrong PIN. Try again.": "رمز خاطئ. حاول مجدداً.",

  // ── My account ──
  "Your own preferences. They don't change anything for the rest of the team.": "تفضيلاتك الخاصة. لا تغيّر شيئاً لبقية الفريق.",
  "About you": "عنك",
  "Your name": "اسمك",
  "Shown in the activity log and on the counter lock screen.": "يظهر في سجل النشاط وشاشة قفل الكاونتر.",
  "Save name": "حفظ الاسم",
  "Name saved": "تم حفظ الاسم",
  "Look and language": "المظهر واللغة",
  "Language": "اللغة",
  "Colours": "الألوان",
  "Dark is easier on the eyes at the bar in the evening.": "الوضع الداكن أريح للعين في المساء.",
  "Extra security": "حماية إضافية",
  "Ask for a code from your phone when signing in.": "طلب رمز من هاتفك عند تسجيل الدخول.",
  "Set up": "إعداد",
  "Set up two-step sign-in": "إعداد الدخول بخطوتين",
  "Two-step sign-in is on": "الدخول بخطوتين مفعّل",
  "Counter PIN": "رمز الكاونتر",
  "A 4-digit code to unlock the shared counter tablet as yourself.": "رمز من 4 أرقام لفتح جهاز الكاونتر المشترك باسمك.",
  "Change PIN": "تغيير الرمز",
  "Set PIN": "تعيين رمز",
  "Save PIN": "حفظ الرمز",
  "New PIN": "الرمز الجديد",
  "PIN saved": "تم حفظ الرمز",
  "The PIN must be exactly 4 digits.": "يجب أن يكون الرمز 4 أرقام بالضبط.",
  "Avoid easy guesses like 1234 or your birthday. Don't share it with the team.": "تجنّب الرموز السهلة مثل 1234 أو تاريخ ميلادك. لا تشاركه مع الفريق.",
  "Sign-in details": "بيانات الدخول",
  "The email and password you use to open this dashboard.": "البريد وكلمة المرور اللذان تستخدمهما لفتح لوحة التحكم.",
  "Change email": "تغيير البريد",
  "Change password": "تغيير كلمة المرور",
  "Change sign-in email": "تغيير بريد الدخول",
  "Waiting for confirmation": "بانتظار التأكيد",
  "Open the link sent to {email} to finish the change. Until then, keep signing in with {current}.": "افتح الرابط المرسل إلى {email} لإكمال التغيير. حتى ذلك الحين، استمر بالدخول بـ {current}.",
  "We'll email a link to the new address. The change only happens after you open it, so a typo can't lock you out. If a second email arrives at your current address, open that link too.": "سنرسل رابطاً إلى البريد الجديد. لن يتم التغيير إلا بعد فتحه، لذلك لن يمنعك خطأ إملائي من الدخول. إذا وصلتك رسالة ثانية على بريدك الحالي، افتح رابطها أيضاً.",
  "New email": "البريد الجديد",
  "Current password": "كلمة المرور الحالية",
  "Send confirmation link": "إرسال رابط التأكيد",
  "This only changes how you sign in. The address that receives order and message emails is under Messages → Notifications.": "هذا يغيّر بريد الدخول فقط. البريد الذي يستقبل رسائل الطلبات موجود في الرسائل ← الإشعارات.",
  "Enter a valid email address.": "أدخل بريداً إلكترونياً صحيحاً.",
  "That's already your sign-in email.": "هذا هو بريد الدخول الحالي بالفعل.",
  "Enter your current password to confirm it's you.": "أدخل كلمة المرور الحالية للتأكد من هويتك.",
  "That password isn't right.": "كلمة المرور غير صحيحة.",
  "Another account already uses that email.": "هذا البريد مستخدم في حساب آخر.",
  "Couldn't change the email right now. Try again in a moment.": "تعذّر تغيير البريد الآن. حاول بعد قليل.",
  "Confirmation link sent to {email}": "تم إرسال رابط التأكيد إلى {email}",
  "Enter your current password.": "أدخل كلمة المرور الحالية.",
  "The new password needs at least 8 characters.": "كلمة المرور الجديدة تحتاج 8 أحرف على الأقل.",
  "The two new passwords don't match.": "كلمتا المرور الجديدتان غير متطابقتين.",
  "Choose a password different from the current one.": "اختر كلمة مرور مختلفة عن الحالية.",
  "Your current password isn't right.": "كلمة المرور الحالية غير صحيحة.",
  "That password is too easy to guess. Try a longer one.": "كلمة المرور سهلة التخمين. جرّب أطول منها.",
  "Couldn't change the password right now. Try again in a moment.": "تعذّر تغيير كلمة المرور الآن. حاول بعد قليل.",
  "Password changed. Use the new one next time you sign in.": "تم تغيير كلمة المرور. استخدم الجديدة في المرة القادمة.",
  "At least 8 characters. A short sentence is easy to remember and hard to guess.": "8 أحرف على الأقل. الجملة القصيرة سهلة التذكر وصعبة التخمين.",
  "Type the new password again": "اكتب كلمة المرور الجديدة مرة أخرى",
  "Save new password": "حفظ كلمة المرور الجديدة",
  "Forgot the current one? Sign out and use “Forgot password?” on the sign-in screen.": "نسيت الحالية؟ سجّل الخروج واستخدم «نسيت كلمة المرور؟» في شاشة الدخول.",
  "Weak": "ضعيفة",
  "Okay": "مقبولة",
  "Strong": "قوية",

  // ── Today ──
  "Here's what needs you right now.": "هذا ما يحتاجك الآن.",
  "New orders": "طلبات جديدة",
  "Waiting to be started": "بانتظار البدء",
  "All caught up": "لا يوجد شيء معلّق",
  "In progress": "قيد التنفيذ",
  "Preparing or ready": "قيد التحضير أو جاهز",
  "Today's sales": "مبيعات اليوم",
  "{n} orders": "{n} طلبات",
  "Unread messages": "رسائل غير مقروءة",
  "From the contact form": "من نموذج التواصل",
  "Waiting now": "بالانتظار الآن",
  "Open the board": "فتح لوحة الطلبات",
  "No open orders": "لا توجد طلبات مفتوحة",
  "New orders will appear here and on the board.": "ستظهر الطلبات الجديدة هنا وفي لوحة الطلبات.",
  "New messages": "رسائل جديدة",
  "All messages": "كل الرسائل",
  "Nothing unread": "لا يوجد غير مقروء",
  "Quick actions": "إجراءات سريعة",
  "Add a menu item": "إضافة صنف للمنيو",
  "Mark something sold out": "تحديد صنف كنفد",
  "Pause online orders": "إيقاف الطلبات مؤقتاً",
  "Edit website pages": "تعديل صفحات الموقع",
  "Find an order": "البحث عن طلب",

  // ── Orders ──
  "01 — Pick-up": "٠١ — الاستلام",
  "Orders.": "الطلبات",
  "New orders appear here by themselves. Tap an order to see everything in it.": "تظهر الطلبات الجديدة هنا تلقائياً. اضغط على الطلب لرؤية تفاصيله.",
  "Add phone or walk-in order": "إضافة طلب هاتفي أو حضوري",
  "Orders view": "عرض الطلبات",
  "Live board": "اللوحة المباشرة",
  "All orders": "كل الطلبات",
  "New": "جديد",
  "Preparing": "قيد التحضير",
  "Ready for pickup": "جاهز للاستلام",
  "Collected": "تم الاستلام",
  "Cancelled": "ملغي",
  "Not collected": "لم يُستلم",
  "Start preparing": "بدء التحضير",
  "Mark ready": "جاهز",
  "No new orders.": "لا توجد طلبات جديدة.",
  "Nothing being made.": "لا شيء قيد التحضير.",
  "Nothing waiting on the counter.": "لا شيء بانتظار الاستلام.",
  "Updates every 15 seconds.": "يتحدث كل 15 ثانية.",
  "Sound on": "الصوت مفعّل",
  "Turn on sound for new orders": "تشغيل صوت للطلبات الجديدة",
  "New order": "طلب جديد",
  "Finished today ({n})": "المنتهية اليوم ({n})",
  "{ref} is now “{status}”": "{ref} الآن «{status}»",
  "Pick-up {time}": "الاستلام {time}",
  "As soon as ready": "فور الجاهزية",
  "As soon as it's ready": "فور جاهزيته",
  "Order number, name, email, phone or item": "رقم الطلب، الاسم، البريد، الهاتف أو الصنف",
  "From": "من",
  "To": "إلى",
  "Where from": "المصدر",
  "Everywhere": "الكل",
  "Phone order": "طلب هاتفي",
  "Walk-in": "حضوري",
  "Last 7 days": "آخر 7 أيام",
  "Last 30 days": "آخر 30 يوماً",
  "Any time": "أي وقت",
  "Download spreadsheet": "تنزيل جدول بيانات",
  "{n} selected": "تم تحديد {n}",
  "Mark collected": "تم الاستلام",
  "{n} orders updated": "تم تحديث {n} طلبات",
  "No orders match": "لا توجد طلبات مطابقة",
  "Try another filter, or clear the search.": "جرّب فلتراً آخر أو امسح البحث.",
  "{n} orders · {total} after refunds (cancelled not counted)": "{n} طلبات · {total} بعد المبالغ المستردة (دون الملغية)",
  "Order": "الطلب",
  "Customer": "العميل",
  "Items": "الأصناف",
  "Newer": "الأحدث",
  "Older": "الأقدم",
  "Page {p} of {n}": "صفحة {p} من {n}",
  "Print ticket": "طباعة التذكرة",
  "Placed {when}": "طُلب {when}",
  "Pick-up": "الاستلام",
  "Customer's note": "ملاحظة العميل",
  "Total · cash at the counter": "المجموع · نقداً عند الكاونتر",
  "Refunded": "مسترد",
  "Has ordered {n} times before": "طلب {n} مرات من قبل",
  "Hello {name}, your Mantel order {ref} is ready for pickup.": "مرحباً {name}، طلبك من مانتل {ref} جاهز للاستلام.",
  "Call": "اتصال",
  "Change status": "تغيير الحالة",
  "Cancel order": "إلغاء الطلب",
  "Record a refund": "تسجيل استرداد",
  "Cancelled because: {reason}": "أُلغي بسبب: {reason}",
  "Note for the team": "ملاحظة للفريق",
  "Only staff see this. For example: “Paid, will collect at 5pm”.": "يراها الفريق فقط. مثلاً: «دفع، سيستلم الساعة 5».",
  "Save note": "حفظ الملاحظة",
  "Note saved": "تم حفظ الملاحظة",
  "History": "السجل",
  "Marked “{status}”": "تم التحويل إلى «{status}»",
  "Refund recorded": "تم تسجيل الاسترداد",
  "Note updated": "تم تحديث الملاحظة",
  "Order entered by staff": "طلب أدخله الفريق",
  "Cancel {ref}?": "إلغاء {ref}؟",
  "Keep the order": "إبقاء الطلب",
  "Reason": "السبب",
  "Something else": "سبب آخر",
  "What happened?": "ماذا حدث؟",
  "Retail items in this order go back into stock.": "منتجات المتجر في هذا الطلب ستعود للمخزون.",
  "Customer asked to cancel": "العميل طلب الإلغاء",
  "Item sold out": "الصنف نفد",
  "Café closed": "المقهى مغلق",
  "Duplicate order": "طلب مكرر",
  "Customer didn't reply": "العميل لم يرد",
  "Record a cash refund": "تسجيل استرداد نقدي",
  "Record refund": "تسجيل الاسترداد",
  "Use this when you give money back at the counter, so the day's totals stay right.": "استخدمه عند إرجاع مبلغ عند الكاونتر، ليبقى مجموع اليوم صحيحاً.",
  "Amount given back": "المبلغ المسترد",
  "Up to {max}": "حتى {max}",
  "Enter an amount above zero.": "أدخل مبلغاً أكبر من صفر.",
  "Placed": "وقت الطلب",
  "ASAP": "فوراً",
  "Note": "ملاحظة",
  "Add an order by hand": "إضافة طلب يدوياً",
  "Type of order": "نوع الطلب",
  "Walk-in, already paid": "حضوري، مدفوع",
  "Phone order, to prepare": "طلب هاتفي، للتحضير",
  "Recorded as collected, so it counts in the day's sales and reports.": "يُسجّل كمستلم، فيُحسب في مبيعات اليوم والتقارير.",
  "Goes onto the live board as a new order, like one from the website.": "يظهر في اللوحة المباشرة كطلب جديد، مثل طلبات الموقع.",
  "Find an item": "ابحث عن صنف",
  "hidden on the website": "مخفي على الموقع",
  "One less {name}": "إنقاص {name}",
  "One more {name}": "زيادة {name}",
  "Customer name": "اسم العميل",
  "Record sale": "تسجيل البيع",
  "Add to the board": "إضافة إلى اللوحة",
  "Add at least one item.": "أضف صنفاً واحداً على الأقل.",
  "Add the customer's name so the counter can call it out.": "أضف اسم العميل لينادى عليه عند الكاونتر.",
  "Sale recorded": "تم تسجيل البيع",
  "Order added to the board": "أُضيف الطلب إلى اللوحة",

  // ── Menu and retail ──
  "Everything customers see on the Menu and Pick Up pages. Changes show on the website within a few minutes.": "كل ما يراه العملاء في صفحتي المنيو والاستلام. تظهر التغييرات على الموقع خلال دقائق.",
  "Change prices": "تغيير الأسعار",
  "Add item": "إضافة صنف",
  "Menu sections": "أقسام المنيو",
  "Categories": "الفئات",
  "Drink options": "خيارات المشروبات",
  "On the website": "على الموقع",
  "Sold out today": "نفد اليوم",
  "Not showing right now": "لا يظهر حالياً",
  "Out of stock": "نفد المخزون",
  "Change order": "تغيير الترتيب",
  "Search the menu": "ابحث في المنيو",
  "Category": "الفئة",
  "All categories": "كل الفئات",
  "No menu items yet": "لا توجد أصناف بعد",
  "Nothing matches": "لا توجد نتائج مطابقة",
  "Add your first drink or dish and it will appear on the Menu page.": "أضف أول مشروب أو طبق وسيظهر في صفحة المنيو.",
  "Try another filter or search word.": "جرّب فلتراً أو كلمة بحث أخرى.",
  "No price": "بلا سعر",
  "Sold out": "نفد",
  "Back on sale": "متوفر مجدداً",
  "Show on website": "عرض على الموقع",
  "Category to reorder": "الفئة المراد ترتيبها",
  "Save order": "حفظ الترتيب",
  "New order saved": "تم حفظ الترتيب الجديد",
  "Use the arrows to put items in the order they should appear on the menu.": "استخدم الأسهم لترتيب الأصناف كما يجب أن تظهر في المنيو.",
  "Move {name} up": "تحريك {name} للأعلى",
  "Move {name} down": "تحريك {name} للأسفل",
  "Give {name} a price before showing it on the website.": "حدّد سعراً لـ {name} قبل عرضه على الموقع.",
  "{name} is on the website": "{name} معروض على الموقع",
  "{name} is hidden": "{name} مخفي",
  "{name} is sold out until tomorrow morning": "{name} نفد حتى صباح الغد",
  "{name} is back on sale": "{name} متوفر مجدداً",
  "{name} archived": "تمت أرشفة {name}",
  "{name} restored": "تمت استعادة {name}",
  "{name} deleted": "تم حذف {name}",
  "{name} saved": "تم حفظ {name}",
  "{name} added": "تمت إضافة {name}",
  "Delete {name} for good?": "حذف {name} نهائياً؟",
  "Past orders keep its name and price, but the item itself can't be brought back. Archiving is usually the better choice.": "الطلبات السابقة تحتفظ باسمه وسعره، لكن لا يمكن استعادة الصنف. الأرشفة عادةً خيار أفضل.",
  "Copy created. It's hidden until you're ready.": "تم إنشاء نسخة، وهي مخفية حتى تجهز.",
  "New menu item": "صنف جديد",
  "The basics": "الأساسيات",
  "Short description": "وصف قصير",
  "Give the item a name.": "أعطِ الصنف اسماً.",
  "The price can't be below zero.": "لا يمكن أن يكون السعر أقل من صفر.",
  "An item needs a price above zero to show on the website.": "يحتاج الصنف سعراً أكبر من صفر ليظهر على الموقع.",
  "Add an end time too, or clear both.": "أضف وقت النهاية أيضاً أو امسح الاثنين.",
  "Add a start time too, or clear both.": "أضف وقت البداية أيضاً أو امسح الاثنين.",
  "Show on the website": "عرض على الموقع",
  "Customers can see it on the menu.": "يراه العملاء في المنيو.",
  "Hidden. Only the team can see it here.": "مخفي. يراه الفريق هنا فقط.",
  "Hides it until 4am tomorrow, then it comes back by itself.": "يخفيه حتى الرابعة فجراً ثم يعود تلقائياً.",
  "Sold out until tomorrow morning": "نفد حتى صباح الغد",
  "Only show it on certain dates or at certain times": "عرضه في تواريخ أو أوقات محددة فقط",
  "From date": "من تاريخ",
  "Until date": "حتى تاريخ",
  "Each day from": "يومياً من",
  "Each day until": "يومياً حتى",
  "For seasonal drinks or breakfast-only food. Leave any box empty to not limit it. Times are Bahrain time.": "للمشروبات الموسمية أو أطعمة الإفطار. اترك أي خانة فارغة لعدم التقييد. الأوقات بتوقيت البحرين.",
  "Photo": "الصورة",
  "Menu photo": "صورة المنيو",
  "A square photo works best. It's resized automatically.": "الصورة المربعة أفضل. يتم تغيير حجمها تلقائياً.",
  "Labels and allergens": "الوسوم ومسببات الحساسية",
  "Help customers choose, and keep people with allergies safe.": "ساعد العملاء على الاختيار واحمِ من لديهم حساسية.",
  "Labels": "الوسوم",
  "Contains": "يحتوي على",
  "Suitable for": "مناسب لـ",
  "Ingredients and nutrition": "المكونات والقيمة الغذائية",
  "Leave a box empty if you don't know it. Empty is never shown as zero.": "اترك الخانة فارغة إذا لم تعرفها. الفارغ لا يظهر كصفر أبداً.",
  "Ingredients": "المكونات",
  "Calories": "السعرات",
  "Protein (g)": "البروتين (غ)",
  "Carbs (g)": "الكربوهيدرات (غ)",
  "Fat (g)": "الدهون (غ)",
  "Choices customers pick when they order, like size or milk. Manage the list under the Drink options tab.": "خيارات يختارها العملاء عند الطلب مثل الحجم أو الحليب. أدِرها من تبويب خيارات المشروبات.",
  "No options yet. Create them under Menu → Drink options.": "لا توجد خيارات بعد. أنشئها من المنيو ← خيارات المشروبات.",
  "Roughly how it reads on the menu.": "تقريباً كما يظهر في المنيو.",
  "Item name": "اسم الصنف",
  "This item is archived": "هذا الصنف مؤرشف",
  "It's hidden everywhere. Use Restore on the menu list to bring it back.": "مخفي في كل مكان. استخدم «استعادة» في قائمة المنيو لإرجاعه.",
  "Leave without saving?": "المغادرة دون حفظ؟",
  "Your changes to this item will be lost.": "ستفقد تغييراتك على هذا الصنف.",
  "Your changes to this product will be lost.": "ستفقد تغييراتك على هذا المنتج.",
  "Remove {name}?": "إزالة {name}؟",
  "Archiving hides it everywhere but keeps it so you can bring it back. Past orders are never affected.": "الأرشفة تخفيه في كل مكان مع الاحتفاظ به لإرجاعه لاحقاً. الطلبات السابقة لا تتأثر.",
  "This can't be undone.": "لا يمكن التراجع عن هذا.",
  "Signature": "مميز",
  "Seasonal": "موسمي",
  "Best seller": "الأكثر مبيعاً",
  "Limited": "كمية محدودة",
  "Dairy": "ألبان",
  "Gluten": "غلوتين",
  "Tree nuts": "مكسرات",
  "Peanuts": "فول سوداني",
  "Egg": "بيض",
  "Soy": "صويا",
  "Sesame": "سمسم",
  "Fish": "سمك",
  "Shellfish": "قشريات",
  "Vegan": "نباتي صرف",
  "Vegetarian": "نباتي",
  "Gluten-free": "خالٍ من الغلوتين",
  "Dairy-free": "خالٍ من الألبان",
  "No added sugar": "بدون سكر مضاف",
  "Raise or lower many prices at once. Use a minus sign to lower them, for example -10.": "ارفع أو اخفض عدة أسعار دفعة واحدة. استخدم علامة السالب للتخفيض، مثل ‎-10.",
  "Which items": "أي أصناف",
  "The whole menu": "المنيو بالكامل",
  "Change by (%)": "التغيير (%)",
  "Round to": "التقريب إلى",
  "Nearest 50 fils (BD 1.550)": "أقرب 50 فلس (1.550 د.ب)",
  "Nearest 100 fils (BD 1.600)": "أقرب 100 فلس (1.600 د.ب)",
  "Nearest 250 fils (BD 1.750)": "أقرب 250 فلس (1.750 د.ب)",
  "No rounding": "بدون تقريب",
  "Item": "الصنف",
  "New price": "السعر الجديد",
  "Update {n} prices": "تحديث {n} أسعار",
  "{n} prices updated": "تم تحديث {n} أسعار",
  "Enter a percentage to see the new prices before anything changes.": "أدخل نسبة لرؤية الأسعار الجديدة قبل أي تغيير.",
  "The headings on the Menu page, in this order.": "عناوين صفحة المنيو بهذا الترتيب.",
  "Add category": "إضافة فئة",
  "{n} items": "{n} أصناف",
  "Show on menu": "عرض في المنيو",
  "{name} is on the menu": "{name} ظاهر في المنيو",
  "{name} is hidden from the menu": "{name} مخفي من المنيو",
  "Move or archive the items in {name} first.": "انقل أو أرشف أصناف {name} أولاً.",
  "Delete {name}?": "حذف {name}؟",
  "Give the category a name.": "أعطِ الفئة اسماً.",
  "Use at least one English letter or number in the name.": "استخدم حرفاً إنجليزياً أو رقماً واحداً على الأقل في الاسم.",
  "Category saved": "تم حفظ الفئة",
  "New category": "فئة جديدة",
  "Edit category": "تعديل الفئة",
  "Web address: bymantel.com/menu/{slug}": "رابط الصفحة: bymantel.com/menu/{slug}",
  "Renaming keeps the same web address, so shared links keep working.": "تغيير الاسم يُبقي نفس الرابط، فتظل الروابط المشاركة تعمل.",
  "Options appear when customers order ahead on the Pick Up page, for example size, milk or an extra shot. Prices add to the item's price.": "تظهر الخيارات عند الطلب المسبق من صفحة الاستلام، مثل الحجم أو الحليب أو شوت إضافي. تُضاف أسعارها إلى سعر الصنف.",
  "Add option": "إضافة خيار",
  "No drink options yet": "لا توجد خيارات مشروبات بعد",
  "Add one, like “Milk: Full cream, Oat (+BD 0.200)”, then tick it on each drink that offers it.": "أضف خياراً مثل «الحليب: كامل الدسم، شوفان (+0.200 د.ب)»، ثم فعّله لكل مشروب يقدمه.",
  "New option": "خيار جديد",
  "Option name": "اسم الخيار",
  "What the customer is choosing, like “Size” or “Milk”.": "ما يختاره العميل، مثل «الحجم» أو «الحليب».",
  "Customer must choose at least": "يجب أن يختار العميل على الأقل",
  "0 means optional.": "0 يعني اختياري.",
  "Customer can choose up to": "يمكن للعميل اختيار حتى",
  "Choices": "الاختيارات",
  "Choice": "الاختيار",
  "choice": "اختيار",
  "Remove choice": "إزالة الاختيار",
  "Adds to the price": "يُضاف إلى السعر",
  "Available": "متوفر",
  "Chosen by default": "مختار افتراضياً",
  "Add a choice": "إضافة اختيار",
  "Give the option a name, like “Milk”.": "أعطِ الخيار اسماً، مثل «الحليب».",
  "Add at least one choice.": "أضف اختياراً واحداً على الأقل.",
  "Every choice needs a name.": "كل اختيار يحتاج اسماً.",
  "Options saved": "تم حفظ الخيارات",
  "It's used by {n} menu items. They'll stop offering it.": "يستخدمه {n} أصناف وستتوقف عن عرضه.",
  "Retail / small editions": "المتجر / إصدارات صغيرة",
  "Retail shop.": "المتجر",
  "The objects on the Retail page. Photos, prices, stock and the words on each product page.": "منتجات صفحة المتجر: الصور والأسعار والمخزون ونصوص كل منتج.",
  "Add product": "إضافة منتج",
  "Low stock": "مخزون منخفض",
  "Search products": "ابحث في المنتجات",
  "{n} in stock": "{n} في المخزون",
  "Use the arrows to set the order on the Retail page.": "استخدم الأسهم لترتيب صفحة المتجر.",
  "New product": "منتج جديد",
  "Give the product a name.": "أعطِ المنتج اسماً.",
  "Use lowercase English letters, numbers and dashes.": "استخدم حروفاً إنجليزية صغيرة وأرقاماً وشرطات.",
  "A product needs a price above zero to show on the website.": "يحتاج المنتج سعراً أكبر من صفر ليظهر على الموقع.",
  "Web address": "رابط الصفحة",
  "Changing this breaks links people have already shared.": "تغييره يعطّل الروابط التي شاركها الناس.",
  "Filled in from the name.": "يُملأ تلقائياً من الاسم.",
  "One-line spec": "مواصفات بسطر واحد",
  "For example: Soy wax · 165g · 45 hours": "مثلاً: شمع الصويا · 165غ · 45 ساعة",
  "Shown on the shelf card and in the bag.": "يظهر على بطاقة المنتج وفي السلة.",
  "Customers can see and buy it.": "يراه العملاء ويمكنهم شراؤه.",
  "Sold out for today": "نفد لهذا اليوم",
  "Hides it until 4am tomorrow.": "يخفيه حتى الرابعة فجراً.",
  "Stock": "المخزون",
  "Count stock for this product": "احتساب المخزون لهذا المنتج",
  "The count goes down with each order and back up if an order is cancelled. At zero it's hidden automatically.": "ينقص العدد مع كل طلب ويعود عند الإلغاء. عند الصفر يُخفى تلقائياً.",
  "In stock now": "المتوفر الآن",
  "Warn me when it gets down to": "نبّهني عندما يصل إلى",
  "Photos": "الصور",
  "Product photos": "صور المنتج",
  "The first photo is the main one. Cut-outs on a transparent background match the rest of the shelf best.": "الصورة الأولى هي الرئيسية. الصور المقصوصة بخلفية شفافة تناسب بقية المتجر.",
  "The product page": "صفحة المنتج",
  "The three folding sections under the price.": "الأقسام الثلاثة القابلة للطي تحت السعر.",
  "The object": "المنتج",
  "Care": "العناية",
  "Collection": "المجموعة",
  "New products are hidden until you switch on “Show on the website”.": "المنتجات الجديدة مخفية حتى تفعّل «عرض على الموقع».",

  // ── Photos ──
  "Drop a photo here, or use the buttons below": "اسحب صورة إلى هنا أو استخدم الأزرار بالأسفل",
  "Current built-in photo": "الصورة الحالية المدمجة",
  "Replace photo": "استبدال الصورة",
  "Upload photo": "رفع صورة",
  "Upload photos": "رفع صور",
  "Choose from library": "اختيار من المكتبة",
  "Use built-in photo": "استخدام الصورة المدمجة",
  "Photo uploaded": "تم رفع الصورة",
  "{n} photos uploaded": "تم رفع {n} صور",
  "Showing the built-in photos until you upload your own:": "تظهر الصور المدمجة حتى ترفع صورك:",
  "Main": "رئيسية",
  "Move earlier": "تقديم",
  "Move later": "تأخير",
  "Remove photo": "إزالة الصورة",
  "Search photos by description": "ابحث في الصور بالوصف",
  "No photos yet": "لا توجد صور بعد",
  "Photos you upload anywhere in the dashboard appear here so you can use them again.": "الصور التي ترفعها في أي مكان تظهر هنا لاستخدامها مجدداً.",
  "That file isn't a photo. Choose a JPG, PNG or WebP image.": "هذا الملف ليس صورة. اختر صورة JPG أو PNG أو WebP.",
  "That photo is too large. Choose one under 25 MB.": "الصورة كبيرة جداً. اختر صورة أقل من 25 ميغابايت.",
  "This photo couldn't be read. Try saving it as JPG and uploading again.": "تعذّرت قراءة الصورة. احفظها كـ JPG وارفعها مجدداً.",
  "You don't have permission to upload photos.": "ليست لديك صلاحية رفع الصور.",
  "The upload failed. Check the connection and try again.": "فشل الرفع. تحقق من الاتصال وحاول مجدداً.",
  "The photo couldn't be deleted. Try again.": "تعذّر حذف الصورة. حاول مجدداً.",

  // ── Messages ──
  "02 — Client care": "٠٢ — خدمة العملاء",
  "Messages.": "الرسائل",
  "Everything sent through the Contact page. A copy also arrives by email.": "كل ما يُرسل من صفحة التواصل. تصل نسخة أيضاً بالبريد.",
  "To do": "للمتابعة",
  "Unread": "غير مقروءة",
  "Done": "تمت",
  "Search messages": "ابحث في الرسائل",
  "Nothing to do": "لا شيء للمتابعة",
  "No messages here": "لا توجد رسائل هنا",
  "New messages from the website appear here.": "تظهر رسائل الموقع الجديدة هنا.",
  "Message": "رسالة",
  "Mark as done": "تمت المتابعة",
  "Move back to to-do": "إرجاع للمتابعة",
  "Marked as done": "تم وضعها كمنتهية",
  "Marked as {status}": "تم التحويل إلى {status}",
  "Read": "مقروءة",
  "Contact": "التواصل",
  "Reply by email": "الرد بالبريد",
  "Re: your message to Mantel": "رد: رسالتك إلى مانتل",

  // ── Marketing ──
  "03 — Keep in touch": "٠٣ — ابقَ على تواصل",
  "Marketing.": "التسويق",
  "Newsletter subscribers now; campaigns, promo codes and loyalty are on their way.": "مشتركو النشرة الآن، والحملات وأكواد الخصم وبرنامج الولاء قادمة.",
  "Marketing sections": "أقسام التسويق",
  "Subscribers": "المشتركون",
  "Newsletters": "النشرات",
  "Promo codes": "أكواد الخصم",
  "Loyalty & gift cards": "الولاء وبطاقات الهدايا",
  "Receiving the newsletter": "يستلمون النشرة",
  "New this month": "جدد هذا الشهر",
  "Subscribed": "مشترك",
  "Unsubscribed": "ألغى الاشتراك",
  "Search emails": "ابحث في البريد",
  "No subscribers here yet": "لا يوجد مشتركون بعد",
  "People who sign up on the home page appear here.": "يظهر هنا من يشترك من الصفحة الرئيسية.",
  "Since {date}": "منذ {date}",
  "{email} will receive the newsletter": "سيستلم {email} النشرة",
  "{email} unsubscribed": "ألغى {email} الاشتراك",
  "02 — Website": "02 — الموقع",
  "04 — Your guests": "04 — ضيوفك",
  "05 — How it's going": "05 — كيف تسير الأمور",
  "06 — Behind the counter": "06 — خلف الكاونتر",
  "07 — Under the hood": "07 — خلف الكواليس",
  "1 hour without use": "ساعة بدون استخدام",
  "15 minutes without use": "15 دقيقة بدون استخدام",
  "3 or more orders from one device": "3 طلبات أو أكثر من جهاز واحد",
  "30 minutes without use": "30 دقيقة بدون استخدام",
  "4 hours without use": "4 ساعات بدون استخدام",
  "Activity log": "سجل النشاط",
  "Add a person": "إضافة شخص",
  "Add a person to the team": "إضافة شخص إلى الفريق",
  "Add to the team": "أضف إلى الفريق",
  "Admins can always do everything": "مدير النظام يستطيع دائمًا فعل كل شيء",
  "After": "بعد",
  "After refunds": "بعد المبالغ المستردة",
  "After their password, each person also enters a 6-digit code from an app on their phone. People who haven't set it up will be asked to the next time they sign in.": "بعد كلمة المرور، يُدخل كل شخص رمزًا من 6 أرقام من تطبيق على هاتفه. من لم يفعّلها بعد سيُطلب منه ذلك عند تسجيل الدخول التالي.",
  "All times are Bahrain time. Refunds are taken off the sales totals.": "جميع الأوقات بتوقيت البحرين. تُخصم المبالغ المستردة من إجمالي المبيعات.",
  "Answered with code {code}": "رد برمز {code}",
  "Anyone who places an order appears here.": "يظهر هنا كل من يضع طلبًا.",
  "Applies to everyone on the team.": "ينطبق على كل الفريق.",
  "Area": "القسم",
  "Ask them to create an account on {site} with this exact email, then open {url}. They'll be let in automatically.": "اطلب منهم إنشاء حساب على {site} بنفس هذا البريد، ثم فتح {url}. سيتم إدخالهم تلقائيًا.",
  "Average order": "متوسط الطلب",
  "Backup downloaded. Keep it somewhere safe.": "تم تنزيل النسخة الاحتياطية. احفظها في مكان آمن.",
  "Before": "قبل",
  "Best sellers": "الأكثر مبيعًا",
  "Block online orders": "منع الطلبات عبر الإنترنت",
  "Blocked": "محظور",
  "Blocked from ordering online": "ممنوع من الطلب عبر الإنترنت",
  "Busiest hours": "أكثر الساعات ازدحامًا",
  "Busy devices today": "أجهزة نشطة جدًا اليوم",
  "By number sold": "حسب عدد المبيعات",
  "Came back": "عادوا مرة أخرى",
  "Can open the dashboard": "يستطيع فتح لوحة التحكم",
  "Cancel invite": "إلغاء الدعوة",
  "Cancel the invite for {email}?": "إلغاء الدعوة لـ {email}؟",
  "Cash over the whole period": "النقد خلال الفترة كاملة",
  "Cash to count": "النقد المطلوب عدّه",
  "Change details": "تفاصيل التغيير",
  "Choose a start date before the end date": "اختر تاريخ بداية قبل تاريخ النهاية",
  "Choose dates": "اختيار التواريخ",
  "Copy link": "نسخ الرابط",
  "Couldn't copy. Press and hold the link to copy it instead.": "تعذر النسخ. اضغط مطولًا على الرابط لنسخه.",
  "Customers are grouped by email address. Guests who order without an account appear too.": "يُجمع العملاء حسب البريد الإلكتروني. يظهر أيضًا الضيوف الذين طلبوا بدون حساب.",
  "Customers.": "العملاء.",
  "Day": "اليوم",
  "Delete photo": "حذف الصورة",
  "Delete their data": "حذف بياناتهم",
  "Delete this customer's personal data?": "حذف البيانات الشخصية لهذا العميل؟",
  "Delete this photo?": "حذف هذه الصورة؟",
  "Delivered": "تم التوصيل",
  "Description": "الوصف",
  "Details are below. If something keeps happening, send a screenshot of this page to your developer.": "التفاصيل بالأسفل. إذا تكرر شيء ما، أرسل لقطة شاشة من هذه الصفحة إلى المطوّر.",
  "Device {id}": "جهاز {id}",
  "Download a backup": "تنزيل نسخة احتياطية",
  "Download for the accountant": "تنزيل للمحاسب",
  "Download their data": "تنزيل بياناتهم",
  "Emails": "الرسائل الإلكترونية",
  "Emails sent": "رسائل مرسلة",
  "Errors in 7 days": "أخطاء خلال 7 أيام",
  "Errors the website reported by itself. Similar errors are grouped.": "أخطاء أبلغ عنها الموقع تلقائيًا. تُجمع الأخطاء المتشابهة معًا.",
  "Every change made in the dashboard is written here: who, what and when.": "كل تغيير في لوحة التحكم يُسجل هنا: من، وماذا، ومتى.",
  "Every photo uploaded to the dashboard, ready to reuse on the menu, the shop and the website.": "كل صورة رُفعت إلى لوحة التحكم، جاهزة لإعادة الاستخدام في المنيو والمتجر والموقع.",
  "Everyone": "الجميع",
  "Everyone must use two-step sign-in": "يجب على الجميع استخدام التحقق بخطوتين",
  "Everyone who has ordered, with their history, notes and privacy requests.": "كل من طلب، مع سجله وملاحظاته وطلبات الخصوصية.",
  "Everything": "كل شيء",
  "Everything looks healthy": "كل شيء يعمل بشكل سليم",
  "Failed": "فشل",
  "Field": "الحقل",
  "First order": "أول طلب",
  "Fixed": "تم الإصلاح",
  "For a shared computer at the counter. Counter tablets using a PIN lock separately.": "لجهاز كمبيوتر مشترك عند الكاونتر. أجهزة الكاونتر التي تستخدم رمز PIN تُقفل بشكل منفصل.",
  "For when a customer asks what you hold about them, or asks you to delete it.": "عندما يسأل العميل عن البيانات المحفوظة عنه، أو يطلب حذفها.",
  "Guest": "ضيف",
  "Has a counter PIN.": "لديه رمز PIN للكاونتر.",
  "Has an account": "لديه حساب",
  "Has an account — just needs to open the dashboard": "لديه حساب — يحتاج فقط لفتح لوحة التحكم",
  "Hasn't signed in yet": "لم يسجل الدخول بعد",
  "If it's still used on the menu, the shop or the website, that spot will show no photo. This can't be undone.": "إذا كانت مستخدمة في المنيو أو المتجر أو الموقع، سيظهر ذلك المكان بدون صورة. لا يمكن التراجع عن ذلك.",
  "Invite cancelled": "تم إلغاء الدعوة",
  "Invite saved for {email}": "تم حفظ الدعوة لـ {email}",
  "Invited {when}": "دُعي {when}",
  "Joined {date}": "انضم في {date}",
  "Last seen {when}": "آخر ظهور {when}",
  "Last visit": "آخر زيارة",
  "Link copied": "تم نسخ الرابط",
  "Mark as fixed": "تحديد كمُصلح",
  "Mark as seen": "تحديد كمُطّلع عليه",
  "Marked as fixed": "تم التحديد كمُصلح",
  "Marked as seen": "تم التحديد كمُطّلع عليه",
  "Menu & retail": "المنيو والمتجر",
  "Menu items": "أصناف المنيو",
  "Needs to create an account first": "يحتاج لإنشاء حساب أولًا",
  "Never": "أبدًا",
  "New-order alerts": "تنبيهات الطلبات الجديدة",
  "Newsletter": "النشرة البريدية",
  "Newsletter subscribers": "مشتركو النشرة",
  "No counter PIN yet.": "لا يوجد رمز PIN للكاونتر بعد.",
  "No customers here yet": "لا يوجد عملاء هنا بعد",
  "No description": "بدون وصف",
  "No email given": "بدون بريد إلكتروني",
  "No emails sent yet.": "لم تُرسل أي رسائل بعد.",
  "No field details were recorded.": "لم تُسجل تفاصيل الحقول.",
  "No one matches that search": "لا أحد يطابق هذا البحث",
  "No open problems, and emails are going out.": "لا توجد مشاكل مفتوحة، والرسائل تُرسل بشكل طبيعي.",
  "No orders yet.": "لا توجد طلبات بعد.",
  "No photos match that search": "لا توجد صور تطابق هذا البحث",
  "No problems reported": "لم يتم الإبلاغ عن مشاكل",
  "No reason given.": "لم يُذكر سبب.",
  "No sales in this period": "لا توجد مبيعات في هذه الفترة",
  "Notes": "ملاحظات",
  "Notes for the team": "ملاحظات للفريق",
  "Nothing recorded yet": "لم يُسجل شيء بعد",
  "Nothing sent recently.": "لم يُرسل شيء مؤخرًا.",
  "On the menu but sold once or not at all in this period.": "موجودة في المنيو لكنها بيعت مرة واحدة أو لم تُبع إطلاقًا في هذه الفترة.",
  "On the newsletter": "مشتركون في النشرة",
  "One device placing many orders can be a prank. Check these orders before preparing them.": "جهاز واحد يضع طلبات كثيرة قد يكون مزحة. تحقق من هذه الطلبات قبل تحضيرها.",
  "Only staff can see these.": "يراها الموظفون فقط.",
  "Open problems": "مشاكل مفتوحة",
  "Order confirmations and other emails the website sent.": "تأكيدات الطلبات والرسائل الأخرى التي أرسلها الموقع.",
  "Orders by day of the week and hour. Darker means busier.": "الطلبات حسب يوم الأسبوع والساعة. اللون الأغمق يعني ازدحامًا أكثر.",
  "Paid in cash at pickup": "مدفوع نقدًا عند الاستلام",
  "Period": "الفترة",
  "Personal data deleted from {n} orders": "حُذفت البيانات الشخصية من {n} طلبات",
  "Photo deleted": "تم حذف الصورة",
  "Photo details": "تفاصيل الصورة",
  "Photo library.": "مكتبة الصور.",
  "Photos are shrunk automatically before uploading, so they load quickly on phones.": "تُصغّر الصور تلقائيًا قبل الرفع لتفتح بسرعة على الهواتف.",
  "Press Enter after each tag. Tags become filters on the list.": "اضغط Enter بعد كل وسم. تصبح الوسوم فلاتر في القائمة.",
  "Print": "طباعة",
  "Privacy": "الخصوصية",
  "Problems": "المشاكل",
  "Read aloud to blind visitors and used by Google. Describe what's in the photo.": "يُقرأ للزوار المكفوفين ويستخدمه Google. صف ما في الصورة.",
  "Recent, none failed": "حديثة، لم يفشل أي منها",
  "Refunded: {amount}": "المسترد: {amount}",
  "Regular": "زبون دائم",
  "Regulars": "الزبائن الدائمون",
  "Reopen": "إعادة فتح",
  "Reports.": "التقارير.",
  "Retail products": "منتجات المتجر",
  "Role": "الدور",
  "Sales": "المبيعات",
  "Sales by category": "المبيعات حسب الفئة",
  "Sales by day": "المبيعات حسب اليوم",
  "Sales, best sellers and your busiest hours. Cancelled orders are left out.": "المبيعات والأكثر مبيعًا وأكثر ساعاتك ازدحامًا. الطلبات الملغاة غير محسوبة.",
  "Saved": "تم الحفظ",
  "Search name, email or phone": "ابحث بالاسم أو البريد أو الهاتف",
  "Security": "الأمان",
  "Security settings saved": "تم حفظ إعدادات الأمان",
  "Seen": "تم الاطلاع",
  "Seen in visitors' browsers": "ظهرت في متصفحات الزوار",
  "Sent": "أُرسلت",
  "Show as a table": "عرض كجدول",
  "Show more": "عرض المزيد",
  "Showing {n} of {total}": "عرض {n} من {total}",
  "Sign out automatically after": "تسجيل الخروج تلقائيًا بعد",
  "Sign-in security": "أمان تسجيل الدخول",
  "Site health.": "صحة الموقع.",
  "Skipped": "تم التخطي",
  "Slow movers": "الأصناف بطيئة البيع",
  "So there's always someone who can fix access. Change what managers and support staff can open below.": "حتى يوجد دائمًا من يستطيع إصلاح الصلاحيات. غيّر ما يستطيع المدراء وموظفو الدعم فتحه بالأسفل.",
  "Spent": "المبلغ المنفق",
  "Switch off": "إيقاف",
  "Switch off when someone leaves. Their history stays in the activity log.": "أوقفه عندما يغادر شخص ما. يبقى سجله في سجل النشاط.",
  "Switch off {name}'s access?": "إيقاف صلاحية {name}؟",
  "Switched off": "موقوف",
  "Tags": "الوسوم",
  "Team sections": "أقسام الفريق",
  "Team.": "الفريق.",
  "The backup file contains all of this.": "ملف النسخة الاحتياطية يحتوي على كل هذا.",
  "The messages the website sends out when an order comes in.": "الرسائل التي يرسلها الموقع عند وصول طلب.",
  "The system": "النظام",
  "The website reports its own errors here automatically. You don't need to do anything unless something is marked open.": "يبلغ الموقع عن أخطائه هنا تلقائيًا. لا تحتاج لفعل شيء إلا إذا كان هناك شيء مفتوح.",
  "Their data was downloaded. Send the file to them by email.": "تم تنزيل بياناتهم. أرسل الملف لهم بالبريد الإلكتروني.",
  "Their email": "بريدهم الإلكتروني",
  "Their name": "اسمهم",
  "Their name, email and phone are removed from past orders, and their messages, newsletter sign-up, notes and account are deleted. Sales totals stay. This can't be undone.": "يُزال اسمهم وبريدهم وهاتفهم من الطلبات السابقة، وتُحذف رسائلهم واشتراكهم في النشرة وملاحظاتهم وحسابهم. تبقى إجماليات المبيعات. لا يمكن التراجع عن ذلك.",
  "They already have an account. They can open {url} now.": "لديهم حساب بالفعل. يمكنهم فتح {url} الآن.",
  "They join automatically the first time they sign in with this email.": "ينضمون تلقائيًا أول مرة يسجلون الدخول بهذا البريد.",
  "They won't be able to open the dashboard or use their counter PIN. You can switch them back on at any time.": "لن يتمكنوا من فتح لوحة التحكم أو استخدام رمز PIN. يمكنك إعادة تفعيلهم في أي وقت.",
  "They won't be able to place orders on the website.": "لن يتمكنوا من وضع طلبات على الموقع.",
  "This month": "هذا الشهر",
  "This was deleted.": "تم حذف هذا.",
  "This was newly added.": "تمت إضافة هذا حديثًا.",
  "Try a longer period.": "جرّب فترة أطول.",
  "Two-step on": "التحقق بخطوتين مفعّل",
  "Two-step sign-in is off.": "التحقق بخطوتين غير مفعّل.",
  "Two-step sign-in is on.": "التحقق بخطوتين مفعّل.",
  "Uploaded {date}": "رُفعت في {date}",
  "Usually orders": "يطلب عادةً",
  "Waiting to join": "بانتظار الانضمام",
  "Website pages & photos": "صفحات الموقع والصور",
  "What": "ماذا",
  "What each role can do": "صلاحيات كل دور",
  "What's stored": "ما هو محفوظ",
  "Where orders came from": "مصدر الطلبات",
  "Whether the website is working, and a backup button for peace of mind.": "هل الموقع يعمل، وزر نسخة احتياطية لراحة البال.",
  "Who": "من",
  "Who can open this dashboard, and what each person can do.": "من يستطيع فتح لوحة التحكم، وما يستطيع كل شخص فعله.",
  "Yesterday": "أمس",
  "You can't switch off your own access.": "لا يمكنك إيقاف صلاحيتك بنفسك.",
  "added": "أضاف",
  "changed": "غيّر",
  "deleted": "حذف",
  "e.g. Always asks for extra hot": "مثال: يطلبها دائمًا ساخنة جدًا",
  "e.g. Iced latte on the marble counter": "مثال: لاتيه مثلج على الكاونتر الرخامي",
  "e.g. Three orders not collected": "مثال: ثلاث طلبات لم تُستلم",
  "e.g. vip, oat-milk": "مثال: vip، حليب-شوفان",
  "last {when}": "آخر مرة {when}",
  "you": "أنت",
  "{change} vs the period before": "{change} مقارنة بالفترة السابقة",
  "{day} {hour}:00 — {n} orders": "{day} {hour}:00 — {n} طلبات",
  "{email} is on the team": "{email} أصبح في الفريق",
  "{n} failed": "فشل {n}",
  "{n} items sold": "بيع {n} صنف",
  "{n} not collected": "{n} لم تُستلم",
  "{n} people can open the dashboard": "{n} أشخاص يستطيعون فتح لوحة التحكم",
  "{n} photos": "{n} صور",
  "{n} things need a look": "{n} أمور تحتاج نظرة",
  "{n} times": "{n} مرات",
  "{n} without a description": "{n} بدون وصف",
  "{role} can use {area}": "{role} يستطيع استخدام {area}",
  "Retail": "المتجر",
  "Other": "أخرى",
  "Menu item": "صنف في المنيو",
  "Menu category": "فئة المنيو",
  "Option group": "مجموعة خيارات",
  "Option": "خيار",
  "Retail product": "منتج في المتجر",
  "Shop setting": "إعداد المتجر",
  "Website text": "نص الموقع",
  "Team member": "عضو في الفريق",
  "Invite": "دعوة",
  "Role permission": "صلاحية الدور",
  "Customer note": "ملاحظة عميل",
  "Everything, including the team and security.": "كل شيء، بما في ذلك الفريق والأمان.",
  "Runs the café and the website. Can't change the team.": "يدير المقهى والموقع. لا يستطيع تغيير الفريق.",
  "Orders and messages only. Good for baristas.": "الطلبات والرسائل فقط. مناسب للباريستا.",
  "See and update orders, print tickets, take phone orders": "عرض الطلبات وتحديثها، طباعة التذاكر، استلام الطلبات الهاتفية",
  "Items, prices, photos, sold out": "الأصناف والأسعار والصور ونفاد الكمية",
  "Text on the website and the photo library": "نصوص الموقع ومكتبة الصور",
  "Opening hours, pausing orders, announcements": "ساعات العمل، إيقاف الطلبات، الإعلانات",
  "Customer list, notes, blocking, privacy requests": "قائمة العملاء، الملاحظات، الحظر، طلبات الخصوصية",
  "The contact-form inbox": "صندوق رسائل نموذج التواصل",
  "Newsletter, promo codes, loyalty": "النشرة، أكواد الخصم، الولاء",
  "Sales numbers and downloads": "أرقام المبيعات والتنزيلات",
  "Card payments and refunds": "الدفع بالبطاقة والمبالغ المستردة",
  "Errors, email delivery, backups": "الأخطاء، إرسال البريد، النسخ الاحتياطية",
  "Invite people and change what they can do": "دعوة الأشخاص وتغيير صلاحياتهم",
  "A page hit an error in a visitor's browser": "حدث خطأ في صفحة على متصفح زائر",
  "Something failed to load in a visitor's browser": "فشل تحميل شيء في متصفح زائر",
  "A page was slow to load": "صفحة كانت بطيئة في التحميل",
  "01 — Paperwork": "01 — الأوراق",
  "Add VAT ({rate}%)": "إضافة ضريبة القيمة المضافة ({rate}%)",
  "Add a line": "إضافة سطر",
  "Add at least one line before issuing the invoice.": "أضف سطرًا واحدًا على الأقل قبل إصدار الفاتورة.",
  "Add who the invoice is for before issuing it.": "أضف اسم من تصدر له الفاتورة قبل إصدارها.",
  "Address": "العنوان",
  "All invoices": "كل الفواتير",
  "Bill to": "الفاتورة إلى",
  "CR number": "رقم السجل التجاري",
  "Company": "الشركة",
  "Copied into a new draft": "تم النسخ إلى مسودة جديدة",
  "Copy into a new invoice": "نسخ إلى فاتورة جديدة",
  "Date": "التاريخ",
  "Days to pay": "أيام السداد",
  "Default note": "الملاحظة الافتراضية",
  "Delete draft": "حذف المسودة",
  "Delete this draft?": "حذف هذه المسودة؟",
  "Details": "التفاصيل",
  "Download as Word": "تنزيل كملف Word",
  "Draft": "مسودة",
  "Draft deleted": "تم حذف المسودة",
  "Draft invoice": "مسودة فاتورة",
  "Draft saved": "تم حفظ المسودة",
  "Drafts": "المسودات",
  "Due date": "تاريخ الاستحقاق",
  "Fill it in, check the preview, then issue it to give it a number.": "املأ البيانات، راجع المعاينة، ثم أصدرها لتحصل على رقم.",
  "Filled in on new invoices. You can change it on each one.": "تُضاف تلقائيًا للفواتير الجديدة. يمكنك تغييرها في كل فاتورة.",
  "Footer": "التذييل",
  "For": "إلى",
  "Instagram": "إنستغرام",
  "Invoice date": "تاريخ الفاتورة",
  "Invoice sections": "أقسام الفواتير",
  "Invoice settings": "إعدادات الفواتير",
  "Invoice settings saved": "تم حفظ إعدادات الفواتير",
  "Invoice voided": "تم إلغاء الفاتورة",
  "Invoice {number} issued": "تم إصدار الفاتورة {number}",
  "Invoices": "الفواتير",
  "Invoices & letterhead": "الفواتير والترويسة",
  "Invoices & letterhead.": "الفواتير والترويسة.",
  "Invoices are numbered like {example}. Numbers never repeat or skip.": "تُرقّم الفواتير هكذا {example}. الأرقام لا تتكرر ولا تُتخطى.",
  "Invoices can then add VAT, show your VAT number and say “Tax invoice”.": "عندها يمكن للفواتير إضافة الضريبة وإظهار رقمك الضريبي وكتابة “فاتورة ضريبية”.",
  "Issue invoice": "إصدار الفاتورة",
  "Issue this invoice?": "إصدار هذه الفاتورة؟",
  "Issued. Waiting to be paid.": "صدرت. بانتظار السداد.",
  "It gets the next invoice number and can't be edited after that. If something is wrong later, you void it and make a new one.": "ستأخذ رقم الفاتورة التالي ولا يمكن تعديلها بعد ذلك. إذا اكتشفت خطأ لاحقًا، ألغها وأنشئ فاتورة جديدة.",
  "Leave empty for {n} days after the invoice date.": "اتركه فارغًا ليكون بعد {n} أيام من تاريخ الفاتورة.",
  "Leave empty to use the day you issue it.": "اتركه فارغًا لاستخدام يوم الإصدار.",
  "Leave one empty to hide it.": "اترك أيًا منهما فارغًا لإخفائه.",
  "Letterhead": "الترويسة",
  "Letterhead saved. New invoices and order emails use it now.": "تم حفظ الترويسة. الفواتير الجديدة ورسائل الطلبات تستخدمها الآن.",
  "Logo": "الشعار",
  "Made from an order": "أُنشئت من طلب",
  "Make an invoice": "إنشاء فاتورة",
  "Make invoices on the café letterhead, and change what the letterhead says.": "أنشئ فواتير على ترويسة المقهى، وغيّر ما تحتويه الترويسة.",
  "Make one from scratch, or open an order and choose “Make an invoice”.": "أنشئ فاتورة من البداية، أو افتح طلبًا واختر “إنشاء فاتورة”.",
  "Mark as paid": "تحديد كمدفوعة",
  "Mark as unpaid": "تحديد كغير مدفوعة",
  "Marked as paid": "تم التحديد كمدفوعة",
  "Marked as unpaid": "تم التحديد كغير مدفوعة",
  "New invoice": "فاتورة جديدة",
  "No invoices match": "لا توجد فواتير مطابقة",
  "No invoices yet": "لا توجد فواتير بعد",
  "Notes on the invoice": "ملاحظات على الفاتورة",
  "Number": "الرقم",
  "Number starts with": "يبدأ الرقم بـ",
  "Numbering": "الترقيم",
  "One letterhead for everything": "ترويسة واحدة لكل شيء",
  "Open order": "فتح الطلب",
  "Overdue": "متأخرة",
  "Paid": "مدفوعة",
  "Paid this month": "المدفوع هذا الشهر",
  "Paid {date}": "دُفعت في {date}",
  "Payment": "الدفع",
  "Payment details": "بيانات الدفع",
  "Print or save as PDF": "طباعة أو حفظ PDF",
  "Printed as “CR No.” followed by this.": "يُطبع بعد عبارة “CR No.”.",
  "Printed at the bottom of every invoice.": "يُطبع أسفل كل فاتورة.",
  "Qty": "الكمية",
  "Remove line": "حذف السطر",
  "Reset to the original": "استعادة الأصل",
  "Search number or customer": "ابحث بالرقم أو العميل",
  "Shown as a tax invoice with your VAT number.": "تظهر كفاتورة ضريبية مع رقمك الضريبي.",
  "Shown small in the top corner. A square or wide image with a plain background works best.": "يظهر صغيرًا في الزاوية العليا. الأفضل صورة مربعة أو عريضة بخلفية سادة.",
  "Subtotal": "المجموع الفرعي",
  "The Word file couldn't be made. Try again.": "تعذر إنشاء ملف Word. حاول مرة أخرى.",
  "The café is registered for VAT": "المقهى مسجل في ضريبة القيمة المضافة",
  "The number stays used and the invoice is kept, marked VOID. Make a new invoice if one is still needed.": "يبقى الرقم مستخدمًا وتُحفظ الفاتورة بعلامة ملغاة. أنشئ فاتورة جديدة إذا احتجت.",
  "Their VAT number": "رقمهم الضريبي",
  "This draft has unsaved changes": "في هذه المسودة تغييرات غير محفوظة",
  "This invoice was voided.": "تم إلغاء هذه الفاتورة.",
  "Top of the page": "أعلى الصفحة",
  "Unit price": "سعر الوحدة",
  "Unpaid": "غير مدفوعة",
  "Used for the due date when you don't pick one.": "يُستخدم لتاريخ الاستحقاق إذا لم تختر تاريخًا.",
  "VAT": "ضريبة القيمة المضافة",
  "VAT number": "الرقم الضريبي",
  "VAT rate": "نسبة الضريبة",
  "VAT {rate}%": "الضريبة {rate}%",
  "Void": "ملغاة",
  "Void invoice": "إلغاء الفاتورة",
  "Void this invoice?": "إلغاء هذه الفاتورة؟",
  "Waiting to be paid": "بانتظار السداد",
  "What it's for": "مقابل ماذا",
  "What you set here appears on invoices, on the new-order emails and in the Word letterhead you can download. Invoices already issued keep the letterhead they were issued with.": "ما تضبطه هنا يظهر على الفواتير ورسائل الطلبات الجديدة وملف Word الذي يمكنك تنزيله. الفواتير الصادرة سابقًا تحتفظ بالترويسة التي صدرت بها.",
  "Your VAT registration is off in Invoice settings.": "تسجيل الضريبة غير مفعّل في إعدادات الفواتير.",
  "e.g. Bank, account name, IBAN, BenefitPay number": "مثال: البنك، اسم الحساب، IBAN، رقم BenefitPay",
  "e.g. Coffee catering, 20 people": "مثال: ضيافة قهوة لـ 20 شخصًا",
  "e.g. Wrong amount": "مثال: مبلغ خاطئ",
  "{n} invoices": "{n} فواتير",
  "Invoice": "فاتورة",
  "Issued invoices can't be changed. Void it and make a new one instead.": "لا يمكن تعديل الفواتير الصادرة. ألغها وأنشئ فاتورة جديدة.",
  "That invoice no longer exists. Refresh the page.": "هذه الفاتورة لم تعد موجودة. حدّث الصفحة.",
  "Issue the invoice first.": "أصدر الفاتورة أولًا.",
  "A voided invoice can't be changed.": "لا يمكن تعديل فاتورة ملغاة.",
  "Only drafts can be deleted. Void an issued invoice instead.": "يمكن حذف المسودات فقط. ألغِ الفاتورة الصادرة بدلًا من ذلك.",
  "That order no longer exists.": "هذا الطلب لم يعد موجودًا.",
  "All capitals": "أحرف كبيرة",
  "Arial": "Arial",
  "Back to the original look": "العودة للشكل الأصلي",
  "Bold": "عريض",
  "Colour": "اللون",
  "Company details": "بيانات الشركة",
  "Courier New": "Courier New",
  "EB Garamond": "EB Garamond",
  "Fira Mono": "Fira Mono",
  "Font": "الخط",
  "Footer details": "بيانات التذييل",
  "Formatting for {part}": "تنسيق {part}",
  "Georgia": "Georgia",
  "Italic": "مائل",
  "Letter spacing": "تباعد الأحرف",
  "Logo size": "حجم الشعار",
  "Look of the CR number and address": "شكل رقم السجل والعنوان",
  "Loose": "متباعد قليلًا",
  "Normal": "عادي",
  "Page text": "نص الصفحة",
  "Reset the look": "استعادة الشكل",
  "Sample": "مثال",
  "Size": "الحجم",
  "Small labels (EMAIL, INSTAGRAM, and the headings on invoices)": "العناوين الصغيرة (EMAIL وINSTAGRAM وعناوين الفواتير)",
  "The email address and Instagram name": "البريد الإلكتروني واسم إنستغرام",
  "The writing on invoices, under the letterhead.": "الكتابة على الفواتير أسفل الترويسة.",
  "Tight": "متقارب",
  "Tighter": "متقارب جدًا",
  "Times New Roman": "Times New Roman",
  "Underline": "تسطير",
  "Verdana": "Verdana",
  "Wide": "متباعد",
  "Wider": "متباعد أكثر",
  "Widest": "متباعد جدًا",
  "A name, or a name and a role on the next line.": "اسم، أو اسم ووظيفة في السطر التالي.",
  "Add at least one line before issuing it.": "أضف سطرًا واحدًا على الأقل قبل الإصدار.",
  "Add who it is for before issuing it.": "أضف اسم الجهة قبل الإصدار.",
  "Amount received": "المبلغ المستلم",
  "Dear …,": "عزيزي …،",
  "Document sections": "أقسام المستندات",
  "Documents": "المستندات",
  "Documents.": "المستندات.",
  "Each kind counts up on its own. Numbers never repeat or skip.": "لكل نوع ترقيمه الخاص. الأرقام لا تتكرر ولا تُتخطى.",
  "Invoices start with": "تبدأ الفواتير بـ",
  "Invoices, receipts and letters on the café letterhead, and the letterhead itself.": "الفواتير والإيصالات والخطابات على ترويسة المقهى، والترويسة نفسها.",
  "Issued": "صادر",
  "Issued {date}": "صدر في {date}",
  "Letter": "الخطاب",
  "Letters": "الخطابات",
  "Letters start with": "تبدأ الخطابات بـ",
  "Make a receipt": "إنشاء إيصال",
  "Middle part (all documents)": "الجزء الأوسط (لكل المستندات)",
  "Notes on the receipt": "ملاحظات على الإيصال",
  "Open invoice": "فتح الفاتورة",
  "Paid by": "طريقة الدفع",
  "Receipt for invoice {number}": "إيصال للفاتورة {number}",
  "Receipts": "الإيصالات",
  "Receipts start with": "تبدأ الإيصالات بـ",
  "Received this month": "المستلم هذا الشهر",
  "Settings": "الإعدادات",
  "Sign-off": "الختام",
  "Signed": "التوقيع",
  "Subject": "الموضوع",
  "The letter": "نص الخطاب",
  "The number stays used and the document is kept, marked VOID. Make a new one if it's still needed.": "يبقى الرقم مستخدمًا ويُحفظ المستند بعلامة ملغى. أنشئ مستندًا جديدًا إذا احتجت.",
  "The sign-off (“{signoff} {signature}”) is added underneath. Change it in Settings.": "يُضاف الختام (“{signoff} {signature}”) في الأسفل. غيّره من الإعدادات.",
  "This document was voided.": "تم إلغاء هذا المستند.",
  "What was paid for": "مقابل ماذا دُفع",
  "Write the letter before issuing it.": "اكتب الخطاب قبل إصداره.",
  "Your VAT registration is off in Settings.": "تسجيل الضريبة غير مفعّل في الإعدادات.",
  "e.g. Catering for your event on 12 October": "مثال: ضيافة لفعاليتكم في 12 أكتوبر",
  "e.g. INV-MTL-004 or an order number": "مثال: INV-MTL-004 أو رقم طلب",
  "e.g. Kind regards,": "مثال: مع خالص التحية،",
  "{n} receipts": "{n} إيصالات",
  "All letters": "كل الخطابات",
  "All receipts": "كل الإيصالات",
  "Bank transfer": "تحويل بنكي",
  "BenefitPay": "BenefitPay",
  "Card": "بطاقة",
  "Cash": "نقدًا",
  "Copy into a new letter": "نسخ إلى خطاب جديد",
  "Copy into a new receipt": "نسخ إلى إيصال جديد",
  "Document": "مستند",
  "Draft letter": "مسودة خطاب",
  "Draft receipt": "مسودة إيصال",
  "Issue letter": "إصدار الخطاب",
  "Issue receipt": "إصدار الإيصال",
  "Issue this letter?": "إصدار هذا الخطاب؟",
  "Issue this receipt?": "إصدار هذا الإيصال؟",
  "It gets the next letter number and can't be edited after that. If something is wrong later, you void it and make a new one.": "سيأخذ رقم الخطاب التالي ولا يمكن تعديله بعد ذلك. إذا اكتشفت خطأ لاحقًا، ألغه وأنشئ خطابًا جديدًا.",
  "It gets the next receipt number and can't be edited after that. If something is wrong later, you void it and make a new one.": "سيأخذ رقم الإيصال التالي ولا يمكن تعديله بعد ذلك. إذا اكتشفت خطأ لاحقًا، ألغه وأنشئ إيصالًا جديدًا.",
  "Letter date": "تاريخ الخطاب",
  "Letter voided": "تم إلغاء الخطاب",
  "Letter {number} issued": "تم إصدار الخطاب {number}",
  "Make one from scratch, from an order (“Make a receipt”), or from an invoice once it's paid.": "أنشئ إيصالًا من البداية، أو من طلب (“إنشاء إيصال”)، أو من فاتورة بعد دفعها.",
  "New letter": "خطاب جديد",
  "New receipt": "إيصال جديد",
  "No letters yet": "لا توجد خطابات بعد",
  "No receipts yet": "لا توجد إيصالات بعد",
  "Receipt date": "تاريخ الإيصال",
  "Receipt voided": "تم إلغاء الإيصال",
  "Receipt {number} issued": "تم إصدار الإيصال {number}",
  "Received from": "استُلم من",
  "Search number, name or subject": "ابحث بالرقم أو الاسم أو الموضوع",
  "Void letter": "إلغاء الخطاب",
  "Void receipt": "إلغاء الإيصال",
  "Write a letter on the café letterhead, then print it or save it as a PDF.": "اكتب خطابًا على ترويسة المقهى، ثم اطبعه أو احفظه PDF.",
  "That document no longer exists. Refresh the page.": "هذا المستند لم يعد موجودًا. حدّث الصفحة.",
  "Issued documents can't be changed. Void it and make a new one instead.": "لا يمكن تعديل المستندات الصادرة. ألغه وأنشئ مستندًا جديدًا.",
  "Issue it first.": "أصدره أولًا.",
  "A voided document can't be changed.": "لا يمكن تعديل مستند ملغى.",
  "Only drafts can be deleted. Void an issued document instead.": "يمكن حذف المسودات فقط. ألغِ المستند الصادر بدلًا من ذلك.",
  "Download": "تنزيل",
  "Word document on the letterhead": "ملف Word على الترويسة",
  "Opens on a phone, looks right when printed or sent.": "يفتح على الهاتف ويبدو مرتبًا عند الطباعة أو الإرسال.",
  "Spreadsheet": "جدول بيانات",
  "For Excel, Numbers or the accountant.": "لـ Excel أو Numbers أو المحاسب.",
  "Making the document…": "جارٍ تجهيز الملف…",
  "Sales report": "تقرير المبيعات",
  "Since": "منذ",
  "Sold": "المُباع",
  "Source": "المصدر",

  // ── Shop settings ──
  "0 means no minimum.": "صفر يعني بدون حد أدنى.",
  "08 — How the shop runs": "08 — تشغيل المحل",
  "A box that opens once for each visitor. After you change it, everyone sees it once more.": "نافذة تظهر مرة واحدة لكل زائر. بعد أي تعديل تظهر للجميع مرة أخرى.",
  "A closing time of 12:00 am means midnight. A closing time earlier than the opening time runs past midnight.": "وقت إغلاق 12:00 صباحًا يعني منتصف الليل. وقت إغلاق قبل وقت الفتح يعني أن اليوم يمتد بعد منتصف الليل.",
  "A line across the top of every page. Good for opening times on a holiday, a new drink, or an event.": "سطر أعلى كل صفحة. مناسب لأوقات العمل في العطل أو مشروب جديد أو فعالية.",
  "Add days off": "إضافة أيام إغلاق",
  "Already passed": "انتهى",
  "Announcement": "الإعلان",
  "Announcement bar": "شريط الإعلان",
  "Announcements": "الإعلانات",
  "Back-soon page": "صفحة \"نعود قريبًا\"",
  "Between 1 and 20. Bigger orders can message you.": "من 1 إلى 20. الطلبات الأكبر تتواصل معكم برسالة.",
  "Blank: straight away": "فارغ: فورًا",
  "Blank: until you turn it off": "فارغ: حتى توقفه",
  "Blank: “Find out more”": "فارغ: “Find out more”",
  "Blank: “We're making a few changes. Back very soon.”": "فارغ: “We're making a few changes. Back very soon.”",
  "Button link": "رابط الزر",
  "Button text": "نص الزر",
  "Check the days off first.": "راجع أيام الإغلاق أولًا.",
  "Check the highlighted fields.": "راجع الحقول المحددة.",
  "Closed": "مغلق",
  "Days off": "أيام الإغلاق",
  "Ended": "انتهى",
  "Every page will show the back-soon message and nobody can order online until you turn it off. This dashboard keeps working.": "كل الصفحات ستعرض رسالة \"نعود قريبًا\" ولن يستطيع أحد الطلب أونلاين حتى توقفها. لوحة التحكم تبقى تعمل.",
  "Every week": "كل أسبوع",
  "First day": "أول يوم",
  "For when the website needs to be hidden for a while — a big menu change, or a problem. The café's own address and Instagram stay on the page.": "عندما تحتاج لإخفاء الموقع فترة — تغيير كبير في المنيو أو مشكلة. عنوان المقهى وإنستغرام يبقيان في الصفحة.",
  "Give the popup a title, or turn it off": "اكتب عنوانًا للنافذة أو أوقفها",
  "Hide after": "إخفاء بعد",
  "Hide the website": "إخفاء الموقع",
  "Hide the website and show the back-soon page": "إخفاء الموقع وعرض صفحة \"نعود قريبًا\"",
  "Hide the website?": "إخفاء الموقع؟",
  "Holidays and other days the café is closed. Online orders stop on these days when “Only during opening hours” is on.": "العطل والأيام الأخرى التي يُغلق فيها المقهى. تتوقف الطلبات أونلاين في هذه الأيام عند تفعيل “فقط خلال أوقات العمل”.",
  "Last day": "آخر يوم",
  "Leave blank for one day": "اتركه فارغًا ليوم واحد",
  "Link": "الرابط",
  "Link text": "نص الرابط",
  "Message while orders are paused": "الرسالة أثناء إيقاف الطلبات",
  "Minimum order": "الحد الأدنى للطلب",
  "Most items in one order": "أقصى عدد قطع في الطلب",
  "No days off planned.": "لا توجد أيام إغلاق مخططة.",
  "Off": "متوقف",
  "Off: people can order any time, even when you're closed.": "متوقف: يمكن الطلب في أي وقت حتى وأنتم مغلقون.",
  "Online orders": "الطلبات أونلاين",
  "Online orders are back on": "عادت الطلبات أونلاين",
  "Online orders paused": "تم إيقاف الطلبات أونلاين",
  "Only during opening hours": "فقط خلال أوقات العمل",
  "Opening hours": "أوقات العمل",
  "Opening hours saved": "تم حفظ أوقات العمل",
  "Opening hours, pausing orders, and what the website shows. Changes reach the website within a minute or two.": "أوقات العمل وإيقاف الطلبات وما يعرضه الموقع. تصل التغييرات للموقع خلال دقيقة أو دقيقتين.",
  "Opens again {when}.": "يفتح مجددًا {when}.",
  "Optional. Shown above the title.": "اختياري. تظهر فوق العنوان.",
  "Order limits": "حدود الطلب",
  "Orders are open around the clock.": "الطلبات مفتوحة على مدار الساعة.",
  "Outside opening hours.": "خارج أوقات العمل.",
  "Outside your hours, the cart says when you open next.": "خارج أوقات العمل، تعرض السلة موعد الفتح القادم.",
  "Pause orders": "إيقاف الطلبات",
  "Pick a date": "اختر تاريخًا",
  "Popup": "النافذة المنبثقة",
  "Resume orders": "استئناف الطلبات",
  "Saved. The website updates within a minute or two.": "تم الحفظ. يتحدث الموقع خلال دقيقة أو دقيقتين.",
  "Scheduled": "مجدول",
  "Shop settings sections": "أقسام إعدادات المحل",
  "Shop settings.": "إعدادات المحل.",
  "Show from": "العرض من",
  "Show the announcement bar": "عرض شريط الإعلان",
  "Show the popup": "عرض النافذة المنبثقة",
  "Showing now": "معروض الآن",
  "Shown in the cart. Leave blank for: “Online orders are paused for now. Please come by the café.”": "تظهر في السلة. اتركها فارغة لعرض: “Online orders are paused for now. Please come by the café.”",
  "Text": "النص",
  "The last day is before the first": "آخر يوم قبل أول يوم",
  "The website is hidden": "الموقع مخفي",
  "The website is not taking orders right now.": "الموقع لا يستقبل طلبات الآن.",
  "The website is showing the back-soon page.": "الموقع يعرض صفحة \"نعود قريبًا\".",
  "The website is taking orders right now.": "الموقع يستقبل الطلبات الآن.",
  "The website now shows the back-soon page": "الموقع يعرض الآن صفحة \"نعود قريبًا\"",
  "Title": "العنوان",
  "Today is marked as closed.": "اليوم محدد كيوم إغلاق.",
  "Until {when}.": "حتى {when}.",
  "Use a full link starting with https://, or a page like /menu": "استخدم رابطًا كاملًا يبدأ بـ https:// أو صفحة مثل /menu",
  "Use {day}'s hours every day": "استخدام أوقات {day} لكل الأيام",
  "Visitors see the back-soon page. Turn it off and save to bring the website back.": "الزوار يرون صفحة \"نعود قريبًا\". أوقفها واحفظ لإرجاع الموقع.",
  "When the website takes orders": "متى يستقبل الموقع الطلبات",
  "Write the announcement, or turn it off": "اكتب الإعلان أو أوقفه",
  "You paused online orders.": "أنت أوقفت الطلبات أونلاين.",
  "am": "ص",
  "e.g. Eid": "مثال: العيد",
  "midnight": "منتصف الليل",
  "pm": "م",
  "today at {time}": "اليوم الساعة {time}",
  "tomorrow at {time}": "غدًا الساعة {time}",
  "{day} at {time}": "{day} الساعة {time}",
  "{day} closes": "إغلاق {day}",
  "{day} opens": "فتح {day}",
  "Download PDF": "تنزيل PDF",
  "Couldn't make the PDF. Try “Print” instead.": "تعذّر إنشاء ملف PDF. جرّب “طباعة” بدلًا من ذلك.",

  // ── Website pages ──
  "About Us": "من نحن",
  "All pages": "كل الصفحات",
  "Answer": "الجواب",
  "Change the words and photos on the website. Nothing changes for visitors until you press Publish.": "غيّر النصوص والصور في الموقع. لا يتغير شيء للزوار حتى تضغط نشر.",
  "Draft not published": "مسودة غير منشورة",
  "Draft saved. Visitors still see the published version.": "تم حفظ المسودة. الزوار ما زالوا يرون النسخة المنشورة.",
  "Earlier versions": "النسخ السابقة",
  "FAQ": "الأسئلة الشائعة",
  "Friday Espresso": "إسبريسو الجمعة",
  "Go back to the original text": "الرجوع للنص الأصلي",
  "Go back to the original text?": "الرجوع للنص الأصلي؟",
  "Heading": "العنوان",
  "Home page": "الصفحة الرئيسية",
  "Last published {when}": "آخر نشر {when}",
  "Last updated": "آخر تحديث",
  "Main photo": "الصورة الرئيسية",
  "Note 01 on the photo": "الملاحظة 01 على الصورة",
  "Note 02 on the photo": "الملاحظة 02 على الصورة",
  "Nothing has been published from here yet.": "لم يُنشر شيء من هنا بعد.",
  "Nothing here yet": "لا يوجد شيء هنا بعد",
  "Original text": "النص الأصلي",
  "Page": "الصفحة",
  "Photo description": "وصف الصورة",
  "Pick Up": "الاستلام",
  "Press Publish when you're happy with it.": "اضغط نشر عندما تكون راضيًا عنها.",
  "Privacy Policy": "سياسة الخصوصية",
  "Publish": "نشر",
  "Publish {page}?": "نشر {page}؟",
  "Published {when}": "نُشرت {when}",
  "Question": "سؤال",
  "Questions": "الأسئلة",
  "Recipe lines": "سطور الوصفة",
  "Refund Policy": "سياسة الاسترجاع",
  "Save as a draft, or publish to put it live": "احفظها كمسودة أو انشرها لتظهر في الموقع",
  "Sections": "الأقسام",
  "Showing the original text. Nothing has been published from here yet.": "يُعرض النص الأصلي. لم يُنشر شيء من هنا بعد.",
  "Small heading": "عنوان صغير",
  "Special harvest": "محصول خاص",
  "Terms of Service": "شروط الخدمة",
  "Thank-you message": "رسالة الشكر",
  "The boxes are filled with the text the website started with. Nothing changes for visitors until you publish.": "تُملأ الحقول بالنص الذي بدأ به الموقع. لا يتغير شيء للزوار حتى تنشر.",
  "The recipe": "الوصفة",
  "This draft isn't on the website yet": "هذه المسودة ليست في الموقع بعد",
  "Use the original text": "استخدام النص الأصلي",
  "Use this version": "استخدام هذه النسخة",
  "Value": "القيمة",
  "Version loaded. Publish to put it back on the website.": "تم تحميل النسخة. انشرها لإرجاعها للموقع.",
  "View on website": "عرض في الموقع",
  "Visitors will see these changes within a minute or two.": "سيرى الزوار هذه التغييرات خلال دقيقة أو دقيقتين.",
  "Website pages.": "صفحات الموقع.",
  "When ordering ahead is open": "عندما يكون الطلب المسبق مفتوحًا",
  "While ordering ahead is closed": "عندما يكون الطلب المسبق مغلقًا",
  "{page} is live": "{page} منشورة الآن",
  "Add a question": "إضافة سؤال",
  "Add a section": "إضافة قسم",
  "Leave an empty line between paragraphs.": "اترك سطرًا فارغًا بين الفقرات.",
  "Line": "سطر",
  "Opens the Friday Espresso page.": "يفتح صفحة إسبريسو الجمعة.",
  "Opens the contact page.": "يفتح صفحة التواصل.",
  "Opens the menu.": "يفتح المنيو.",
  "Optional. The first section usually has none.": "اختياري. القسم الأول عادةً بدون عنوان.",
  "Read out to people who can't see the photo.": "يُقرأ للأشخاص الذين لا يستطيعون رؤية الصورة.",
  "Section": "قسم",
  "Shown after someone signs up.": "تظهر بعد التسجيل.",
  "Shown under the title, e.g. 31 August 2026. Change it when you change the policy.": "يظهر تحت العنوان، مثال: 31 August 2026. غيّره عند تغيير السياسة.",
  "The large photo at the top. A tall photo works best.": "الصورة الكبيرة في الأعلى. الصورة الطولية أفضل.",
  "The opening hours on this page come from Shop settings.": "أوقات العمل في هذه الصفحة تأتي من إعدادات المحل.",
  "The tray photo and where its numbered notes point stay as they are: they're measured off the picture.": "صورة الصينية ومواضع الملاحظات المرقمة تبقى كما هي، لأنها مقاسة على الصورة.",
  "This section only appears once at least one line has a value.": "يظهر هذا القسم فقط عندما يكون لسطر واحد على الأقل قيمة.",
  "e.g. 18 g in, 36 g out": "مثال: 18 g in, 36 g out",
};
