/*
 * Arabic for every dashboard string, keyed by the English sentence used at the
 * call site. Missing keys fall back to English (see i18n.tsx). Run
 * `node scripts/admin-i18n-check.mjs` to list anything not yet translated.
 */
export const AR: Record<string, string> = {
  // ── Navigation and shell ──
  "Today": "اليوم",
  "Orders": "الطلبات",
  "Menu": "المنيو",
  "Retail shop": "المتجر",
  "Website pages": "صفحات الموقع",
  "Photo library": "مكتبة الصور",
  "Customers": "العملاء",
  "Messages": "الرسائل",
  "Marketing": "التسويق",
  "Reports": "التقارير",
  "Shop settings": "إعدادات المحل",
  "Payments": "المدفوعات",
  "Team": "الفريق",
  "Site health": "صحة الموقع",
  "My account": "حسابي",
  "Run the café": "إدارة المقهى",
  "Website": "الموقع",
  "People": "الناس",
  "Grow": "النمو",
  "Setup": "الإعداد",
  "Staff": "الموظفون",
  "Mantel staff": "فريق مانتل",
  "Mantel — Staff": "مانتل — الفريق",
  "Search": "بحث",
  "Dashboard navigation": "قائمة لوحة التحكم",
  "Open menu": "فتح القائمة",
  "Open the website": "فتح الموقع",
  "Sign out": "تسجيل الخروج",
  "Lock": "قفل",
  "Theme: {mode}": "المظهر: {mode}",
  "Automatic": "تلقائي",
  "Light": "فاتح",
  "Dark": "داكن",
  "{n} need attention": "{n} بحاجة لمتابعة",
  "{n} new": "{n} جديد",
  "Your role doesn't include this section": "صلاحيتك لا تشمل هذا القسم",
  "Ask an admin to change what your role can do under Team → Permissions.": "اطلب من المدير تعديل صلاحياتك من الفريق ← الصلاحيات.",
  "This screen is being built": "هذه الشاشة قيد الإنشاء",
  "It will appear here in the next update.": "ستظهر هنا في التحديث القادم.",
  "Admin": "مدير النظام",
  "Manager": "مدير",
  "Support": "دعم",
  "Good morning": "صباح الخير",
  "Good afternoon": "مساء الخير",
  "Good evening": "مساء الخير",

  // ── Common words and actions ──
  "Add": "إضافة",
  "All": "الكل",
  "Archive": "أرشفة",
  "Archived": "مؤرشف",
  "Back": "رجوع",
  "Cancel": "إلغاء",
  "Clear": "مسح",
  "Clear search": "مسح البحث",
  "Close": "إغلاق",
  "Delete": "حذف",
  "Delete for good": "حذف نهائي",
  "Discard": "تجاهل",
  "Dismiss": "إخفاء",
  "Duplicate": "نسخ",
  "Email": "البريد الإلكتروني",
  "English": "الإنجليزية",
  "Hidden": "مخفي",
  "Leave": "مغادرة",
  "Loading…": "جارٍ التحميل…",
  "Name": "الاسم",
  "Now": "الآن",
  "On": "مفعّل",
  "Open": "مفتوح",
  "optional": "اختياري",
  "Phone": "الهاتف",
  "Preview": "معاينة",
  "Price": "السعر",
  "Remove": "إزالة",
  "Remove {v}": "إزالة {v}",
  "Restore": "استعادة",
  "Results": "النتائج",
  "Save": "حفظ",
  "Save changes": "حفظ التغييرات",
  "Select": "تحديد",
  "Show": "عرض",
  "Status": "الحالة",
  "Total": "المجموع",
  "Try again": "حاول مجدداً",
  "Undo": "تراجع",
  "Verify": "تحقق",
  "WhatsApp": "واتساب",
  "Why": "السبب",
  "Yes, continue": "نعم، متابعة",
  "Unsaved changes": "تغييرات غير محفوظة",
  "You have unsaved changes": "لديك تغييرات غير محفوظة",
  "What does this mean?": "ماذا يعني هذا؟",
  "This didn't load": "لم يتم التحميل",
  "Type \"{word}\" to confirm": "اكتب \"{word}\" للتأكيد",
  "just now": "الآن",
  "{n} min ago": "قبل {n} دقيقة",
  "{n} h ago": "قبل {n} ساعة",
  "{n} days ago": "قبل {n} يوم",
  "Sunday": "الأحد",
  "Monday": "الاثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": "الخميس",
  "Friday": "الجمعة",
  "Saturday": "السبت",
  "Open screen": "فتح الشاشة",
  "Order number, customer, item or screen…": "رقم الطلب، العميل، الصنف أو الشاشة…",
  "Nothing found. Try an order number like MTL-1A2B3C, a name, or an email.": "لا توجد نتائج. جرّب رقم طلب مثل MTL-1A2B3C أو اسماً أو بريداً إلكترونياً.",
  "Leave blank to use the English": "اتركه فارغاً لاستخدام النص الإنجليزي",

  // ── Errors ──
  "Something went wrong. Please try again.": "حدث خطأ ما. حاول مرة أخرى.",
  "Couldn't reach the server. Check the internet connection and try again.": "تعذّر الوصول إلى الخادم. تحقق من الإنترنت وحاول مجدداً.",
  "You don't have permission to do this. Ask an admin to give your role access.": "ليست لديك صلاحية لهذا الإجراء. اطلب من المدير منح صلاحيتك.",
  "That name or code is already used. Choose a different one.": "هذا الاسم أو الرمز مستخدم بالفعل. اختر غيره.",
  "An item needs a price above zero before it can be shown on the website.": "يجب أن يكون للصنف سعر أكبر من صفر قبل عرضه على الموقع.",
  "One of the values isn't allowed. Check the numbers and try again.": "إحدى القيم غير مسموح بها. تحقق من الأرقام وحاول مجدداً.",
  "This is still linked to something else, so it can't be removed. Try archiving it instead.": "هذا مرتبط بشيء آخر ولا يمكن حذفه. جرّب أرشفته بدلاً من ذلك.",
  "One of the values isn't valid.": "إحدى القيم غير صحيحة.",
  "That record no longer exists. Refresh the page.": "هذا السجل لم يعد موجوداً. حدّث الصفحة.",

  // ── Sign in ──
  "Sign in to the dashboard": "الدخول إلى لوحة التحكم",
  "Reset your password": "إعادة تعيين كلمة المرور",
  "For the Mantel team only.": "لفريق مانتل فقط.",
  "Enter your email and we'll send you a link to choose a new password.": "أدخل بريدك وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.",
  "Password": "كلمة المرور",
  "Show password": "إظهار كلمة المرور",
  "Hide password": "إخفاء كلمة المرور",
  "Sign in": "دخول",
  "Send reset link": "إرسال رابط إعادة التعيين",
  "Forgot password?": "نسيت كلمة المرور؟",
  "Back to sign in": "العودة لتسجيل الدخول",
  "Back to the website": "العودة إلى الموقع",
  "Check your email": "تحقق من بريدك",
  "If {email} belongs to a Mantel account, a link to set a new password is on its way. It can take a minute, and sometimes lands in spam.": "إذا كان {email} مرتبطاً بحساب في مانتل، فرابط تعيين كلمة المرور في الطريق. قد يستغرق دقيقة، وأحياناً يصل إلى البريد المزعج.",
  "Enter the email address you use for Mantel.": "أدخل البريد الإلكتروني الذي تستخدمه في مانتل.",
  "This email hasn't been confirmed yet. Open the link we emailed you first.": "لم يتم تأكيد هذا البريد بعد. افتح الرابط الذي أرسلناه لك أولاً.",
  "That email and password don't match. Check them, or reset the password.": "البريد وكلمة المرور غير متطابقين. تحقق منهما أو أعد تعيين كلمة المرور.",
  "Too many attempts. Wait a minute and try again.": "محاولات كثيرة. انتظر دقيقة وحاول مجدداً.",
  "Too many attempts. Wait a few minutes and try again.": "محاولات كثيرة. انتظر بضع دقائق وحاول مجدداً.",
  "Couldn't sign in right now. Check the connection and try again.": "تعذّر تسجيل الدخول الآن. تحقق من الاتصال وحاول مجدداً.",
  "This account isn't on the team": "هذا الحساب ليس ضمن الفريق",
  "Couldn't check your access": "تعذّر التحقق من صلاحيتك",
  "{email} is signed in, but it hasn't been added to the Mantel team. Ask an admin to invite this email under Team.": "تم تسجيل الدخول بـ {email} لكنه غير مضاف إلى فريق مانتل. اطلب من المدير دعوته من قسم الفريق.",
  "Check again": "تحقق مرة أخرى",
  "Sign in with a different account": "الدخول بحساب آخر",
  "Choose a new password": "اختر كلمة مرور جديدة",
  "New password": "كلمة المرور الجديدة",
  "At least 8 characters.": "8 أحرف على الأقل.",
  "Type it again": "اكتبها مرة أخرى",
  "Save password": "حفظ كلمة المرور",
  "Use at least 8 characters.": "استخدم 8 أحرف على الأقل.",
  "The two passwords don't match.": "كلمتا المرور غير متطابقتين.",
  "Couldn't save the new password. Open the link from the email again.": "تعذّر حفظ كلمة المرور. افتح الرابط من البريد مرة أخرى.",

  // ── Two-step and PIN ──
  "Two-step sign-in": "الدخول بخطوتين",
  "The team has turned on two-step sign-in. It keeps customer details safe even if a password is guessed.": "فعّل الفريق الدخول بخطوتين. يحمي بيانات العملاء حتى لو تم تخمين كلمة المرور.",
  "1. Install an authenticator app on your phone, such as Google Authenticator or Microsoft Authenticator.": "١. ثبّت تطبيق مصادقة على هاتفك مثل Google Authenticator أو Microsoft Authenticator.",
  "2. In the app, add an account and scan this code:": "٢. في التطبيق، أضف حساباً وامسح هذا الرمز:",
  "3. Enter the 6-digit code the app shows:": "٣. أدخل الرمز المكوّن من 6 أرقام الظاهر في التطبيق:",
  "QR code for your authenticator app": "رمز QR لتطبيق المصادقة",
  "Can't scan? Type this key into the app instead:": "لا يمكنك المسح؟ اكتب هذا المفتاح في التطبيق:",
  "Open your authenticator app and enter the 6-digit code for Mantel.": "افتح تطبيق المصادقة وأدخل رمز مانتل المكوّن من 6 أرقام.",
  "6-digit code": "رمز من 6 أرقام",
  "That code didn't work. Codes change every 30 seconds — use the newest one.": "الرمز غير صحيح. تتغير الرموز كل 30 ثانية — استخدم أحدثها.",
  "Couldn't start two-step setup. Try again in a moment.": "تعذّر بدء إعداد الدخول بخطوتين. حاول بعد قليل.",
  "Counter locked": "الجهاز مقفل",
  "Who's at the counter?": "من على الكاونتر؟",
  "Enter your PIN": "أدخل رمزك السري",
  "{n} of 4 digits entered": "تم إدخال {n} من 4 أرقام",
  "Delete digit": "حذف رقم",
  "Wrong PIN. Try again.": "رمز خاطئ. حاول مجدداً.",

  // ── My account ──
  "Your own preferences. They don't change anything for the rest of the team.": "تفضيلاتك الخاصة. لا تغيّر شيئاً لبقية الفريق.",
  "About you": "عنك",
  "Your name": "اسمك",
  "Shown in the activity log and on the counter lock screen.": "يظهر في سجل النشاط وشاشة قفل الكاونتر.",
  "Save name": "حفظ الاسم",
  "Name saved": "تم حفظ الاسم",
  "Look and language": "المظهر واللغة",
  "Language": "اللغة",
  "Colours": "الألوان",
  "Dark is easier on the eyes at the bar in the evening.": "الوضع الداكن أريح للعين في المساء.",
  "Extra security": "حماية إضافية",
  "Ask for a code from your phone when signing in.": "طلب رمز من هاتفك عند تسجيل الدخول.",
  "Set up": "إعداد",
  "Set up two-step sign-in": "إعداد الدخول بخطوتين",
  "Two-step sign-in is on": "الدخول بخطوتين مفعّل",
  "Counter PIN": "رمز الكاونتر",
  "A 4-digit code to unlock the shared counter tablet as yourself.": "رمز من 4 أرقام لفتح جهاز الكاونتر المشترك باسمك.",
  "Change PIN": "تغيير الرمز",
  "Set PIN": "تعيين رمز",
  "Save PIN": "حفظ الرمز",
  "New PIN": "الرمز الجديد",
  "PIN saved": "تم حفظ الرمز",
  "The PIN must be exactly 4 digits.": "يجب أن يكون الرمز 4 أرقام بالضبط.",
  "Avoid easy guesses like 1234 or your birthday. Don't share it with the team.": "تجنّب الرموز السهلة مثل 1234 أو تاريخ ميلادك. لا تشاركه مع الفريق.",
  "Sign-in details": "بيانات الدخول",
  "The email and password you use to open this dashboard.": "البريد وكلمة المرور اللذان تستخدمهما لفتح لوحة التحكم.",
  "Change email": "تغيير البريد",
  "Change password": "تغيير كلمة المرور",
  "Change sign-in email": "تغيير بريد الدخول",
  "Waiting for confirmation": "بانتظار التأكيد",
  "Open the link sent to {email} to finish the change. Until then, keep signing in with {current}.": "افتح الرابط المرسل إلى {email} لإكمال التغيير. حتى ذلك الحين، استمر بالدخول بـ {current}.",
  "We'll email a link to the new address. The change only happens after you open it, so a typo can't lock you out. If a second email arrives at your current address, open that link too.": "سنرسل رابطاً إلى البريد الجديد. لن يتم التغيير إلا بعد فتحه، لذلك لن يمنعك خطأ إملائي من الدخول. إذا وصلتك رسالة ثانية على بريدك الحالي، افتح رابطها أيضاً.",
  "New email": "البريد الجديد",
  "Current password": "كلمة المرور الحالية",
  "Send confirmation link": "إرسال رابط التأكيد",
  "This only changes how you sign in. The address that receives order and message emails is under Messages → Notifications.": "هذا يغيّر بريد الدخول فقط. البريد الذي يستقبل رسائل الطلبات موجود في الرسائل ← الإشعارات.",
  "Enter a valid email address.": "أدخل بريداً إلكترونياً صحيحاً.",
  "That's already your sign-in email.": "هذا هو بريد الدخول الحالي بالفعل.",
  "Enter your current password to confirm it's you.": "أدخل كلمة المرور الحالية للتأكد من هويتك.",
  "That password isn't right.": "كلمة المرور غير صحيحة.",
  "Another account already uses that email.": "هذا البريد مستخدم في حساب آخر.",
  "Couldn't change the email right now. Try again in a moment.": "تعذّر تغيير البريد الآن. حاول بعد قليل.",
  "Confirmation link sent to {email}": "تم إرسال رابط التأكيد إلى {email}",
  "Enter your current password.": "أدخل كلمة المرور الحالية.",
  "The new password needs at least 8 characters.": "كلمة المرور الجديدة تحتاج 8 أحرف على الأقل.",
  "The two new passwords don't match.": "كلمتا المرور الجديدتان غير متطابقتين.",
  "Choose a password different from the current one.": "اختر كلمة مرور مختلفة عن الحالية.",
  "Your current password isn't right.": "كلمة المرور الحالية غير صحيحة.",
  "That password is too easy to guess. Try a longer one.": "كلمة المرور سهلة التخمين. جرّب أطول منها.",
  "Couldn't change the password right now. Try again in a moment.": "تعذّر تغيير كلمة المرور الآن. حاول بعد قليل.",
  "Password changed. Use the new one next time you sign in.": "تم تغيير كلمة المرور. استخدم الجديدة في المرة القادمة.",
  "At least 8 characters. A short sentence is easy to remember and hard to guess.": "8 أحرف على الأقل. الجملة القصيرة سهلة التذكر وصعبة التخمين.",
  "Type the new password again": "اكتب كلمة المرور الجديدة مرة أخرى",
  "Save new password": "حفظ كلمة المرور الجديدة",
  "Forgot the current one? Sign out and use “Forgot password?” on the sign-in screen.": "نسيت الحالية؟ سجّل الخروج واستخدم «نسيت كلمة المرور؟» في شاشة الدخول.",
  "Weak": "ضعيفة",
  "Okay": "مقبولة",
  "Strong": "قوية",

  // ── Today ──
  "Here's what needs you right now.": "هذا ما يحتاجك الآن.",
  "New orders": "طلبات جديدة",
  "Waiting to be started": "بانتظار البدء",
  "All caught up": "لا يوجد شيء معلّق",
  "In progress": "قيد التنفيذ",
  "Preparing or ready": "قيد التحضير أو جاهز",
  "Today's sales": "مبيعات اليوم",
  "{n} orders": "{n} طلبات",
  "Unread messages": "رسائل غير مقروءة",
  "From the contact form": "من نموذج التواصل",
  "Waiting now": "بالانتظار الآن",
  "Open the board": "فتح لوحة الطلبات",
  "No open orders": "لا توجد طلبات مفتوحة",
  "New orders will appear here and on the board.": "ستظهر الطلبات الجديدة هنا وفي لوحة الطلبات.",
  "New messages": "رسائل جديدة",
  "All messages": "كل الرسائل",
  "Nothing unread": "لا يوجد غير مقروء",
  "Quick actions": "إجراءات سريعة",
  "Add a menu item": "إضافة صنف للمنيو",
  "Mark something sold out": "تحديد صنف كنفد",
  "Pause online orders": "إيقاف الطلبات مؤقتاً",
  "Edit website pages": "تعديل صفحات الموقع",
  "Find an order": "البحث عن طلب",

  // ── Orders ──
  "01 — Pick-up": "٠١ — الاستلام",
  "Orders.": "الطلبات",
  "New orders appear here by themselves. Tap an order to see everything in it.": "تظهر الطلبات الجديدة هنا تلقائياً. اضغط على الطلب لرؤية تفاصيله.",
  "Add phone or walk-in order": "إضافة طلب هاتفي أو حضوري",
  "Orders view": "عرض الطلبات",
  "Live board": "اللوحة المباشرة",
  "All orders": "كل الطلبات",
  "New": "جديد",
  "Preparing": "قيد التحضير",
  "Ready for pickup": "جاهز للاستلام",
  "Collected": "تم الاستلام",
  "Cancelled": "ملغي",
  "Not collected": "لم يُستلم",
  "Start preparing": "بدء التحضير",
  "Mark ready": "جاهز",
  "No new orders.": "لا توجد طلبات جديدة.",
  "Nothing being made.": "لا شيء قيد التحضير.",
  "Nothing waiting on the counter.": "لا شيء بانتظار الاستلام.",
  "Updates every 15 seconds.": "يتحدث كل 15 ثانية.",
  "Sound on": "الصوت مفعّل",
  "Turn on sound for new orders": "تشغيل صوت للطلبات الجديدة",
  "New order": "طلب جديد",
  "Finished today ({n})": "المنتهية اليوم ({n})",
  "{ref} is now “{status}”": "{ref} الآن «{status}»",
  "Pick-up {time}": "الاستلام {time}",
  "As soon as ready": "فور الجاهزية",
  "As soon as it's ready": "فور جاهزيته",
  "Order number, name, email, phone or item": "رقم الطلب، الاسم، البريد، الهاتف أو الصنف",
  "From": "من",
  "To": "إلى",
  "Where from": "المصدر",
  "Everywhere": "الكل",
  "Phone order": "طلب هاتفي",
  "Walk-in": "حضوري",
  "Last 7 days": "آخر 7 أيام",
  "Last 30 days": "آخر 30 يوماً",
  "Any time": "أي وقت",
  "Download spreadsheet": "تنزيل جدول بيانات",
  "{n} selected": "تم تحديد {n}",
  "Mark collected": "تم الاستلام",
  "{n} orders updated": "تم تحديث {n} طلبات",
  "No orders match": "لا توجد طلبات مطابقة",
  "Try another filter, or clear the search.": "جرّب فلتراً آخر أو امسح البحث.",
  "{n} orders · {total} after refunds (cancelled not counted)": "{n} طلبات · {total} بعد المبالغ المستردة (دون الملغية)",
  "Order": "الطلب",
  "Customer": "العميل",
  "Items": "الأصناف",
  "Newer": "الأحدث",
  "Older": "الأقدم",
  "Page {p} of {n}": "صفحة {p} من {n}",
  "Print ticket": "طباعة التذكرة",
  "Placed {when}": "طُلب {when}",
  "Pick-up": "الاستلام",
  "Customer's note": "ملاحظة العميل",
  "Total · cash at the counter": "المجموع · نقداً عند الكاونتر",
  "Refunded": "مسترد",
  "Has ordered {n} times before": "طلب {n} مرات من قبل",
  "Hello {name}, your Mantel order {ref} is ready for pickup.": "مرحباً {name}، طلبك من مانتل {ref} جاهز للاستلام.",
  "Call": "اتصال",
  "Change status": "تغيير الحالة",
  "Cancel order": "إلغاء الطلب",
  "Record a refund": "تسجيل استرداد",
  "Cancelled because: {reason}": "أُلغي بسبب: {reason}",
  "Note for the team": "ملاحظة للفريق",
  "Only staff see this. For example: “Paid, will collect at 5pm”.": "يراها الفريق فقط. مثلاً: «دفع، سيستلم الساعة 5».",
  "Save note": "حفظ الملاحظة",
  "Note saved": "تم حفظ الملاحظة",
  "History": "السجل",
  "Marked “{status}”": "تم التحويل إلى «{status}»",
  "Refund recorded": "تم تسجيل الاسترداد",
  "Note updated": "تم تحديث الملاحظة",
  "Order entered by staff": "طلب أدخله الفريق",
  "Cancel {ref}?": "إلغاء {ref}؟",
  "Keep the order": "إبقاء الطلب",
  "Reason": "السبب",
  "Something else": "سبب آخر",
  "What happened?": "ماذا حدث؟",
  "Retail items in this order go back into stock.": "منتجات المتجر في هذا الطلب ستعود للمخزون.",
  "Customer asked to cancel": "العميل طلب الإلغاء",
  "Item sold out": "الصنف نفد",
  "Café closed": "المقهى مغلق",
  "Duplicate order": "طلب مكرر",
  "Customer didn't reply": "العميل لم يرد",
  "Record a cash refund": "تسجيل استرداد نقدي",
  "Record refund": "تسجيل الاسترداد",
  "Use this when you give money back at the counter, so the day's totals stay right.": "استخدمه عند إرجاع مبلغ عند الكاونتر، ليبقى مجموع اليوم صحيحاً.",
  "Amount given back": "المبلغ المسترد",
  "Up to {max}": "حتى {max}",
  "Enter an amount above zero.": "أدخل مبلغاً أكبر من صفر.",
  "Placed": "وقت الطلب",
  "ASAP": "فوراً",
  "Note": "ملاحظة",
  "Add an order by hand": "إضافة طلب يدوياً",
  "Type of order": "نوع الطلب",
  "Walk-in, already paid": "حضوري، مدفوع",
  "Phone order, to prepare": "طلب هاتفي، للتحضير",
  "Recorded as collected, so it counts in the day's sales and reports.": "يُسجّل كمستلم، فيُحسب في مبيعات اليوم والتقارير.",
  "Goes onto the live board as a new order, like one from the website.": "يظهر في اللوحة المباشرة كطلب جديد، مثل طلبات الموقع.",
  "Find an item": "ابحث عن صنف",
  "hidden on the website": "مخفي على الموقع",
  "One less {name}": "إنقاص {name}",
  "One more {name}": "زيادة {name}",
  "Customer name": "اسم العميل",
  "Record sale": "تسجيل البيع",
  "Add to the board": "إضافة إلى اللوحة",
  "Add at least one item.": "أضف صنفاً واحداً على الأقل.",
  "Add the customer's name so the counter can call it out.": "أضف اسم العميل لينادى عليه عند الكاونتر.",
  "Sale recorded": "تم تسجيل البيع",
  "Order added to the board": "أُضيف الطلب إلى اللوحة",

  // ── Menu and retail ──
  "Everything customers see on the Menu and Pick Up pages. Changes show on the website within a few minutes.": "كل ما يراه العملاء في صفحتي المنيو والاستلام. تظهر التغييرات على الموقع خلال دقائق.",
  "Change prices": "تغيير الأسعار",
  "Add item": "إضافة صنف",
  "Menu sections": "أقسام المنيو",
  "Categories": "الفئات",
  "Drink options": "خيارات المشروبات",
  "On the website": "على الموقع",
  "Sold out today": "نفد اليوم",
  "Not showing right now": "لا يظهر حالياً",
  "Out of stock": "نفد المخزون",
  "Change order": "تغيير الترتيب",
  "Search the menu": "ابحث في المنيو",
  "Category": "الفئة",
  "All categories": "كل الفئات",
  "No menu items yet": "لا توجد أصناف بعد",
  "Nothing matches": "لا توجد نتائج مطابقة",
  "Add your first drink or dish and it will appear on the Menu page.": "أضف أول مشروب أو طبق وسيظهر في صفحة المنيو.",
  "Try another filter or search word.": "جرّب فلتراً أو كلمة بحث أخرى.",
  "No price": "بلا سعر",
  "Sold out": "نفد",
  "Back on sale": "متوفر مجدداً",
  "Show on website": "عرض على الموقع",
  "Category to reorder": "الفئة المراد ترتيبها",
  "Save order": "حفظ الترتيب",
  "New order saved": "تم حفظ الترتيب الجديد",
  "Use the arrows to put items in the order they should appear on the menu.": "استخدم الأسهم لترتيب الأصناف كما يجب أن تظهر في المنيو.",
  "Move {name} up": "تحريك {name} للأعلى",
  "Move {name} down": "تحريك {name} للأسفل",
  "Give {name} a price before showing it on the website.": "حدّد سعراً لـ {name} قبل عرضه على الموقع.",
  "{name} is on the website": "{name} معروض على الموقع",
  "{name} is hidden": "{name} مخفي",
  "{name} is sold out until tomorrow morning": "{name} نفد حتى صباح الغد",
  "{name} is back on sale": "{name} متوفر مجدداً",
  "{name} archived": "تمت أرشفة {name}",
  "{name} restored": "تمت استعادة {name}",
  "{name} deleted": "تم حذف {name}",
  "{name} saved": "تم حفظ {name}",
  "{name} added": "تمت إضافة {name}",
  "Delete {name} for good?": "حذف {name} نهائياً؟",
  "Past orders keep its name and price, but the item itself can't be brought back. Archiving is usually the better choice.": "الطلبات السابقة تحتفظ باسمه وسعره، لكن لا يمكن استعادة الصنف. الأرشفة عادةً خيار أفضل.",
  "Copy created. It's hidden until you're ready.": "تم إنشاء نسخة، وهي مخفية حتى تجهز.",
  "New menu item": "صنف جديد",
  "The basics": "الأساسيات",
  "Short description": "وصف قصير",
  "Give the item a name.": "أعطِ الصنف اسماً.",
  "The price can't be below zero.": "لا يمكن أن يكون السعر أقل من صفر.",
  "An item needs a price above zero to show on the website.": "يحتاج الصنف سعراً أكبر من صفر ليظهر على الموقع.",
  "Add an end time too, or clear both.": "أضف وقت النهاية أيضاً أو امسح الاثنين.",
  "Add a start time too, or clear both.": "أضف وقت البداية أيضاً أو امسح الاثنين.",
  "Show on the website": "عرض على الموقع",
  "Customers can see it on the menu.": "يراه العملاء في المنيو.",
  "Hidden. Only the team can see it here.": "مخفي. يراه الفريق هنا فقط.",
  "Hides it until 4am tomorrow, then it comes back by itself.": "يخفيه حتى الرابعة فجراً ثم يعود تلقائياً.",
  "Sold out until tomorrow morning": "نفد حتى صباح الغد",
  "Only show it on certain dates or at certain times": "عرضه في تواريخ أو أوقات محددة فقط",
  "From date": "من تاريخ",
  "Until date": "حتى تاريخ",
  "Each day from": "يومياً من",
  "Each day until": "يومياً حتى",
  "For seasonal drinks or breakfast-only food. Leave any box empty to not limit it. Times are Bahrain time.": "للمشروبات الموسمية أو أطعمة الإفطار. اترك أي خانة فارغة لعدم التقييد. الأوقات بتوقيت البحرين.",
  "Photo": "الصورة",
  "Menu photo": "صورة المنيو",
  "A square photo works best. It's resized automatically.": "الصورة المربعة أفضل. يتم تغيير حجمها تلقائياً.",
  "Labels and allergens": "الوسوم ومسببات الحساسية",
  "Help customers choose, and keep people with allergies safe.": "ساعد العملاء على الاختيار واحمِ من لديهم حساسية.",
  "Labels": "الوسوم",
  "Contains": "يحتوي على",
  "Suitable for": "مناسب لـ",
  "Ingredients and nutrition": "المكونات والقيمة الغذائية",
  "Leave a box empty if you don't know it. Empty is never shown as zero.": "اترك الخانة فارغة إذا لم تعرفها. الفارغ لا يظهر كصفر أبداً.",
  "Ingredients": "المكونات",
  "Calories": "السعرات",
  "Protein (g)": "البروتين (غ)",
  "Carbs (g)": "الكربوهيدرات (غ)",
  "Fat (g)": "الدهون (غ)",
  "Choices customers pick when they order, like size or milk. Manage the list under the Drink options tab.": "خيارات يختارها العملاء عند الطلب مثل الحجم أو الحليب. أدِرها من تبويب خيارات المشروبات.",
  "No options yet. Create them under Menu → Drink options.": "لا توجد خيارات بعد. أنشئها من المنيو ← خيارات المشروبات.",
  "Roughly how it reads on the menu.": "تقريباً كما يظهر في المنيو.",
  "Item name": "اسم الصنف",
  "This item is archived": "هذا الصنف مؤرشف",
  "It's hidden everywhere. Use Restore on the menu list to bring it back.": "مخفي في كل مكان. استخدم «استعادة» في قائمة المنيو لإرجاعه.",
  "Leave without saving?": "المغادرة دون حفظ؟",
  "Your changes to this item will be lost.": "ستفقد تغييراتك على هذا الصنف.",
  "Your changes to this product will be lost.": "ستفقد تغييراتك على هذا المنتج.",
  "Remove {name}?": "إزالة {name}؟",
  "Archiving hides it everywhere but keeps it so you can bring it back. Past orders are never affected.": "الأرشفة تخفيه في كل مكان مع الاحتفاظ به لإرجاعه لاحقاً. الطلبات السابقة لا تتأثر.",
  "This can't be undone.": "لا يمكن التراجع عن هذا.",
  "Signature": "مميز",
  "Seasonal": "موسمي",
  "Best seller": "الأكثر مبيعاً",
  "Limited": "كمية محدودة",
  "Dairy": "ألبان",
  "Gluten": "غلوتين",
  "Tree nuts": "مكسرات",
  "Peanuts": "فول سوداني",
  "Egg": "بيض",
  "Soy": "صويا",
  "Sesame": "سمسم",
  "Fish": "سمك",
  "Shellfish": "قشريات",
  "Vegan": "نباتي صرف",
  "Vegetarian": "نباتي",
  "Gluten-free": "خالٍ من الغلوتين",
  "Dairy-free": "خالٍ من الألبان",
  "No added sugar": "بدون سكر مضاف",
  "Raise or lower many prices at once. Use a minus sign to lower them, for example -10.": "ارفع أو اخفض عدة أسعار دفعة واحدة. استخدم علامة السالب للتخفيض، مثل ‎-10.",
  "Which items": "أي أصناف",
  "The whole menu": "المنيو بالكامل",
  "Change by (%)": "التغيير (%)",
  "Round to": "التقريب إلى",
  "Nearest 50 fils (BD 1.550)": "أقرب 50 فلس (1.550 د.ب)",
  "Nearest 100 fils (BD 1.600)": "أقرب 100 فلس (1.600 د.ب)",
  "Nearest 250 fils (BD 1.750)": "أقرب 250 فلس (1.750 د.ب)",
  "No rounding": "بدون تقريب",
  "Item": "الصنف",
  "New price": "السعر الجديد",
  "Update {n} prices": "تحديث {n} أسعار",
  "{n} prices updated": "تم تحديث {n} أسعار",
  "Enter a percentage to see the new prices before anything changes.": "أدخل نسبة لرؤية الأسعار الجديدة قبل أي تغيير.",
  "The headings on the Menu page, in this order.": "عناوين صفحة المنيو بهذا الترتيب.",
  "Add category": "إضافة فئة",
  "{n} items": "{n} أصناف",
  "Show on menu": "عرض في المنيو",
  "{name} is on the menu": "{name} ظاهر في المنيو",
  "{name} is hidden from the menu": "{name} مخفي من المنيو",
  "Move or archive the items in {name} first.": "انقل أو أرشف أصناف {name} أولاً.",
  "Delete {name}?": "حذف {name}؟",
  "Give the category a name.": "أعطِ الفئة اسماً.",
  "Use at least one English letter or number in the name.": "استخدم حرفاً إنجليزياً أو رقماً واحداً على الأقل في الاسم.",
  "Category saved": "تم حفظ الفئة",
  "New category": "فئة جديدة",
  "Edit category": "تعديل الفئة",
  "Web address: bymantel.com/menu/{slug}": "رابط الصفحة: bymantel.com/menu/{slug}",
  "Renaming keeps the same web address, so shared links keep working.": "تغيير الاسم يُبقي نفس الرابط، فتظل الروابط المشاركة تعمل.",
  "Options appear when customers order ahead on the Pick Up page, for example size, milk or an extra shot. Prices add to the item's price.": "تظهر الخيارات عند الطلب المسبق من صفحة الاستلام، مثل الحجم أو الحليب أو شوت إضافي. تُضاف أسعارها إلى سعر الصنف.",
  "Add option": "إضافة خيار",
  "No drink options yet": "لا توجد خيارات مشروبات بعد",
  "Add one, like “Milk: Full cream, Oat (+BD 0.200)”, then tick it on each drink that offers it.": "أضف خياراً مثل «الحليب: كامل الدسم، شوفان (+0.200 د.ب)»، ثم فعّله لكل مشروب يقدمه.",
  "New option": "خيار جديد",
  "Option name": "اسم الخيار",
  "What the customer is choosing, like “Size” or “Milk”.": "ما يختاره العميل، مثل «الحجم» أو «الحليب».",
  "Customer must choose at least": "يجب أن يختار العميل على الأقل",
  "0 means optional.": "0 يعني اختياري.",
  "Customer can choose up to": "يمكن للعميل اختيار حتى",
  "Choices": "الاختيارات",
  "Choice": "الاختيار",
  "choice": "اختيار",
  "Remove choice": "إزالة الاختيار",
  "Adds to the price": "يُضاف إلى السعر",
  "Available": "متوفر",
  "Chosen by default": "مختار افتراضياً",
  "Add a choice": "إضافة اختيار",
  "Give the option a name, like “Milk”.": "أعطِ الخيار اسماً، مثل «الحليب».",
  "Add at least one choice.": "أضف اختياراً واحداً على الأقل.",
  "Every choice needs a name.": "كل اختيار يحتاج اسماً.",
  "Options saved": "تم حفظ الخيارات",
  "It's used by {n} menu items. They'll stop offering it.": "يستخدمه {n} أصناف وستتوقف عن عرضه.",
  "Retail / small editions": "المتجر / إصدارات صغيرة",
  "Retail shop.": "المتجر",
  "The objects on the Retail page. Photos, prices, stock and the words on each product page.": "منتجات صفحة المتجر: الصور والأسعار والمخزون ونصوص كل منتج.",
  "Add product": "إضافة منتج",
  "Low stock": "مخزون منخفض",
  "Search products": "ابحث في المنتجات",
  "{n} in stock": "{n} في المخزون",
  "Use the arrows to set the order on the Retail page.": "استخدم الأسهم لترتيب صفحة المتجر.",
  "New product": "منتج جديد",
  "Give the product a name.": "أعطِ المنتج اسماً.",
  "Use lowercase English letters, numbers and dashes.": "استخدم حروفاً إنجليزية صغيرة وأرقاماً وشرطات.",
  "A product needs a price above zero to show on the website.": "يحتاج المنتج سعراً أكبر من صفر ليظهر على الموقع.",
  "Web address": "رابط الصفحة",
  "Changing this breaks links people have already shared.": "تغييره يعطّل الروابط التي شاركها الناس.",
  "Filled in from the name.": "يُملأ تلقائياً من الاسم.",
  "One-line spec": "مواصفات بسطر واحد",
  "For example: Soy wax · 165g · 45 hours": "مثلاً: شمع الصويا · 165غ · 45 ساعة",
  "Shown on the shelf card and in the bag.": "يظهر على بطاقة المنتج وفي السلة.",
  "Customers can see and buy it.": "يراه العملاء ويمكنهم شراؤه.",
  "Sold out for today": "نفد لهذا اليوم",
  "Hides it until 4am tomorrow.": "يخفيه حتى الرابعة فجراً.",
  "Stock": "المخزون",
  "Count stock for this product": "احتساب المخزون لهذا المنتج",
  "The count goes down with each order and back up if an order is cancelled. At zero it's hidden automatically.": "ينقص العدد مع كل طلب ويعود عند الإلغاء. عند الصفر يُخفى تلقائياً.",
  "In stock now": "المتوفر الآن",
  "Warn me when it gets down to": "نبّهني عندما يصل إلى",
  "Photos": "الصور",
  "Product photos": "صور المنتج",
  "The first photo is the main one. Cut-outs on a transparent background match the rest of the shelf best.": "الصورة الأولى هي الرئيسية. الصور المقصوصة بخلفية شفافة تناسب بقية المتجر.",
  "The product page": "صفحة المنتج",
  "The three folding sections under the price.": "الأقسام الثلاثة القابلة للطي تحت السعر.",
  "The object": "المنتج",
  "Care": "العناية",
  "Collection": "المجموعة",
  "New products are hidden until you switch on “Show on the website”.": "المنتجات الجديدة مخفية حتى تفعّل «عرض على الموقع».",

  // ── Photos ──
  "Drop a photo here, or use the buttons below": "اسحب صورة إلى هنا أو استخدم الأزرار بالأسفل",
  "Current built-in photo": "الصورة الحالية المدمجة",
  "Replace photo": "استبدال الصورة",
  "Upload photo": "رفع صورة",
  "Upload photos": "رفع صور",
  "Choose from library": "اختيار من المكتبة",
  "Use built-in photo": "استخدام الصورة المدمجة",
  "Photo uploaded": "تم رفع الصورة",
  "{n} photos uploaded": "تم رفع {n} صور",
  "Showing the built-in photos until you upload your own:": "تظهر الصور المدمجة حتى ترفع صورك:",
  "Main": "رئيسية",
  "Move earlier": "تقديم",
  "Move later": "تأخير",
  "Remove photo": "إزالة الصورة",
  "Search photos by description": "ابحث في الصور بالوصف",
  "No photos yet": "لا توجد صور بعد",
  "Photos you upload anywhere in the dashboard appear here so you can use them again.": "الصور التي ترفعها في أي مكان تظهر هنا لاستخدامها مجدداً.",
  "That file isn't a photo. Choose a JPG, PNG or WebP image.": "هذا الملف ليس صورة. اختر صورة JPG أو PNG أو WebP.",
  "That photo is too large. Choose one under 25 MB.": "الصورة كبيرة جداً. اختر صورة أقل من 25 ميغابايت.",
  "This photo couldn't be read. Try saving it as JPG and uploading again.": "تعذّرت قراءة الصورة. احفظها كـ JPG وارفعها مجدداً.",
  "You don't have permission to upload photos.": "ليست لديك صلاحية رفع الصور.",
  "The upload failed. Check the connection and try again.": "فشل الرفع. تحقق من الاتصال وحاول مجدداً.",
  "The photo couldn't be deleted. Try again.": "تعذّر حذف الصورة. حاول مجدداً.",

  // ── Messages ──
  "02 — Client care": "٠٢ — خدمة العملاء",
  "Messages.": "الرسائل",
  "Everything sent through the Contact page. A copy also arrives by email.": "كل ما يُرسل من صفحة التواصل. تصل نسخة أيضاً بالبريد.",
  "To do": "للمتابعة",
  "Unread": "غير مقروءة",
  "Done": "تمت",
  "Search messages": "ابحث في الرسائل",
  "Nothing to do": "لا شيء للمتابعة",
  "No messages here": "لا توجد رسائل هنا",
  "New messages from the website appear here.": "تظهر رسائل الموقع الجديدة هنا.",
  "Message": "رسالة",
  "Mark as done": "تمت المتابعة",
  "Move back to to-do": "إرجاع للمتابعة",
  "Marked as done": "تم وضعها كمنتهية",
  "Marked as {status}": "تم التحويل إلى {status}",
  "Read": "مقروءة",
  "Contact": "التواصل",
  "Reply by email": "الرد بالبريد",
  "Re: your message to Mantel": "رد: رسالتك إلى مانتل",

  // ── Marketing ──
  "03 — Keep in touch": "٠٣ — ابقَ على تواصل",
  "Marketing.": "التسويق",
  "Newsletter subscribers now; campaigns, promo codes and loyalty are on their way.": "مشتركو النشرة الآن، والحملات وأكواد الخصم وبرنامج الولاء قادمة.",
  "Marketing sections": "أقسام التسويق",
  "Subscribers": "المشتركون",
  "Newsletters": "النشرات",
  "Promo codes": "أكواد الخصم",
  "Loyalty & gift cards": "الولاء وبطاقات الهدايا",
  "Receiving the newsletter": "يستلمون النشرة",
  "New this month": "جدد هذا الشهر",
  "Subscribed": "مشترك",
  "Unsubscribed": "ألغى الاشتراك",
  "Search emails": "ابحث في البريد",
  "No subscribers here yet": "لا يوجد مشتركون بعد",
  "People who sign up on the home page appear here.": "يظهر هنا من يشترك من الصفحة الرئيسية.",
  "Since {date}": "منذ {date}",
  "{email} will receive the newsletter": "سيستلم {email} النشرة",
  "{email} unsubscribed": "ألغى {email} الاشتراك",
};
